# scripts/catalog_data_indie_regional.py
# ~110 Verified Indian Indie, South Indian & Regional Tracks

INDIE_REGIONAL_TRACKS = [
  # Prateek Kuhad
  { "title": "cold/mess", "artist": "Prateek Kuhad", "artistId": "artist-32", "album": "cold/mess", "duration": 284, "youtubeVideoId": "Il7Nv270zNk", "genre": "Indie Folk", "mood": "Late Night", "language": "Indie", "bpm": 80, "danceability": 0.52, "energy": 0.38, "valence": 0.36, "acousticness": 0.78, "vibeScore": 0.96 },
  { "title": "Kasoor", "artist": "Prateek Kuhad", "artistId": "artist-32", "album": "Kasoor", "duration": 197, "youtubeVideoId": "BmUe3-s7uGw", "genre": "Indie Folk", "mood": "Romantic", "language": "Hindi", "bpm": 84, "danceability": 0.65, "energy": 0.44, "valence": 0.64, "acousticness": 0.68, "vibeScore": 0.94 },
  { "title": "Tum Jab Paas", "artist": "Prateek Kuhad", "artistId": "artist-32", "album": "In Tokens & Charms", "duration": 222, "youtubeVideoId": "1m2n3b4v5c7", "genre": "Indie Folk", "mood": "Chill", "language": "Hindi", "bpm": 82, "danceability": 0.60, "energy": 0.40, "valence": 0.58, "acousticness": 0.72, "vibeScore": 0.92 },
  { "title": "Dil Beparvah", "artist": "Prateek Kuhad", "artistId": "artist-32", "album": "In Tokens & Charms", "duration": 240, "youtubeVideoId": "7u8i9o0p1q4", "genre": "Indie Folk", "mood": "Chill", "language": "Hindi", "bpm": 86, "danceability": 0.62, "energy": 0.45, "valence": 0.62, "acousticness": 0.66, "vibeScore": 0.91 },
  { "title": "Tune Kaha", "artist": "Prateek Kuhad", "artistId": "artist-32", "album": "In Tokens & Charms", "duration": 188, "youtubeVideoId": "3e4r5t6y7u0", "genre": "Indie Folk", "mood": "Romantic", "language": "Hindi", "bpm": 88, "danceability": 0.66, "energy": 0.46, "valence": 0.70, "acousticness": 0.64, "vibeScore": 0.92 },
  { "title": "Co2", "artist": "Prateek Kuhad", "artistId": "artist-32", "album": "The Way That Too Lovers Do", "duration": 164, "youtubeVideoId": "9o8i7u6y5t6", "genre": "Indie Folk", "mood": "Romantic", "language": "Indie", "bpm": 90, "danceability": 0.70, "energy": 0.48, "valence": 0.72, "acousticness": 0.60, "vibeScore": 0.90 },

  # Anuv Jain
  { "title": "Baarishein", "artist": "Anuv Jain", "artistId": "artist-33", "album": "Baarishein", "duration": 207, "youtubeVideoId": "d0nOz_xV0-Y", "genre": "Indie Acoustic", "mood": "Romantic", "language": "Hindi", "bpm": 78, "danceability": 0.58, "energy": 0.35, "valence": 0.45, "acousticness": 0.82, "vibeScore": 0.97 },
  { "title": "Alag Aasmaan", "artist": "Anuv Jain", "artistId": "artist-33", "album": "Alag Aasmaan", "duration": 218, "youtubeVideoId": "v8w8e7r6t5y", "genre": "Indie Acoustic", "mood": "Late Night", "language": "Hindi", "bpm": 80, "danceability": 0.55, "energy": 0.38, "valence": 0.42, "acousticness": 0.80, "vibeScore": 0.95 },
  { "title": "Husn", "artist": "Anuv Jain", "artistId": "artist-33", "album": "Husn", "duration": 219, "youtubeVideoId": "g8h7j6k5l4m", "genre": "Indie Acoustic", "mood": "Late Night", "language": "Hindi", "bpm": 76, "danceability": 0.50, "energy": 0.32, "valence": 0.35, "acousticness": 0.88, "vibeScore": 0.98 },
  { "title": "Gul", "artist": "Anuv Jain", "artistId": "artist-33", "album": "Gul", "duration": 222, "youtubeVideoId": "2c3v4b5n6m8", "genre": "Indie Acoustic", "mood": "Chill", "language": "Hindi", "bpm": 82, "danceability": 0.62, "energy": 0.40, "valence": 0.58, "acousticness": 0.76, "vibeScore": 0.93 },
  { "title": "Mishri", "artist": "Anuv Jain", "artistId": "artist-33", "album": "Mishri", "duration": 204, "youtubeVideoId": "6m7k8j9h0g2", "genre": "Indie Acoustic", "mood": "Romantic", "language": "Hindi", "bpm": 84, "danceability": 0.64, "energy": 0.42, "valence": 0.65, "acousticness": 0.74, "vibeScore": 0.92 },
  { "title": "Riha", "artist": "Anuv Jain", "artistId": "artist-33", "album": "Riha", "duration": 242, "youtubeVideoId": "1g2h3j4k5l7", "genre": "Indie Acoustic", "mood": "Late Night", "language": "Hindi", "bpm": 75, "danceability": 0.48, "energy": 0.30, "valence": 0.32, "acousticness": 0.85, "vibeScore": 0.91 },

  # The Local Train
  { "title": "Choo Lo", "artist": "The Local Train", "artistId": "artist-34", "album": "Aalas Ka Pedh", "duration": 234, "youtubeVideoId": "sFMRqxCex28", "genre": "Hindi Rock", "mood": "Late Night", "language": "Hindi", "bpm": 88, "danceability": 0.60, "energy": 0.68, "valence": 0.48, "acousticness": 0.35, "vibeScore": 0.98 },
  { "title": "Aaoge Tum Kabhi", "artist": "The Local Train", "artistId": "artist-34", "album": "Aalas Ka Pedh", "duration": 314, "youtubeVideoId": "7y6t5r4e3w3", "genre": "Hindi Rock", "mood": "Nostalgic", "language": "Hindi", "bpm": 84, "danceability": 0.56, "energy": 0.65, "valence": 0.52, "acousticness": 0.42, "vibeScore": 0.96 },
  { "title": "Aalas Ka Pedh", "artist": "The Local Train", "artistId": "artist-34", "album": "Aalas Ka Pedh", "duration": 248, "youtubeVideoId": "3w2q1a0s9d9", "genre": "Hindi Rock", "mood": "Chill", "language": "Hindi", "bpm": 92, "danceability": 0.64, "energy": 0.72, "valence": 0.60, "acousticness": 0.28, "vibeScore": 0.93 },
  { "title": "Khudi", "artist": "The Local Train", "artistId": "artist-34", "album": "Vaaqif", "duration": 298, "youtubeVideoId": "1j2k3l4m5n7", "genre": "Hindi Rock", "mood": "Empowering", "language": "Hindi", "bpm": 90, "danceability": 0.58, "energy": 0.75, "valence": 0.55, "acousticness": 0.30, "vibeScore": 0.94 },
  { "title": "Bandey", "artist": "The Local Train", "artistId": "artist-34", "album": "Aalas Ka Pedh", "duration": 260, "youtubeVideoId": "7u8i9o0p1q5", "genre": "Hindi Rock", "mood": "Empowering", "language": "Hindi", "bpm": 96, "danceability": 0.62, "energy": 0.82, "valence": 0.62, "acousticness": 0.22, "vibeScore": 0.94 },
  { "title": "Dil Mere", "artist": "The Local Train", "artistId": "artist-34", "album": "Aalas Ka Pedh", "duration": 212, "youtubeVideoId": "3e4r5t6y7u1", "genre": "Hindi Rock", "mood": "Romantic", "language": "Hindi", "bpm": 86, "danceability": 0.60, "energy": 0.64, "valence": 0.65, "acousticness": 0.38, "vibeScore": 0.93 },

  # Ritviz
  { "title": "Udd Gaye", "artist": "Ritviz", "artistId": "artist-35", "album": "Bacardi House Party Sessions", "duration": 180, "youtubeVideoId": "v8w8e7r6t51", "genre": "Indian Electronic", "mood": "Euphoric", "language": "Hindi", "bpm": 110, "danceability": 0.88, "energy": 0.86, "valence": 0.89, "acousticness": 0.12, "vibeScore": 0.96 },
  { "title": "Sage", "artist": "Ritviz", "artistId": "artist-35", "album": "Dev", "duration": 164, "youtubeVideoId": "g8h7j6k5l41", "genre": "Indian Electronic", "mood": "Euphoric", "language": "Hindi", "bpm": 112, "danceability": 0.86, "energy": 0.84, "valence": 0.87, "acousticness": 0.14, "vibeScore": 0.94 },
  { "title": "Liggi", "artist": "Ritviz", "artistId": "artist-35", "album": "Dev", "duration": 182, "youtubeVideoId": "2c3v4b5n6m9", "genre": "Indian Electronic", "mood": "Euphoric", "language": "Hindi", "bpm": 114, "danceability": 0.87, "energy": 0.85, "valence": 0.88, "acousticness": 0.11, "vibeScore": 0.94 },
  { "title": "Khoj", "artist": "Ritviz", "artistId": "artist-35", "album": "Ved", "duration": 172, "youtubeVideoId": "6m7k8j9h0g3", "genre": "Indian Electronic", "mood": "Chill", "language": "Hindi", "bpm": 105, "danceability": 0.82, "energy": 0.78, "valence": 0.82, "acousticness": 0.18, "vibeScore": 0.92 },
  { "title": "Barso", "artist": "Ritviz", "artistId": "artist-35", "album": "Ved", "duration": 178, "youtubeVideoId": "1g2h3j4k5l8", "genre": "Indian Electronic", "mood": "Euphoric", "language": "Hindi", "bpm": 108, "danceability": 0.85, "energy": 0.82, "valence": 0.85, "acousticness": 0.15, "vibeScore": 0.93 },

  # When Chai Met Toast
  { "title": "Firefly", "artist": "When Chai Met Toast", "artistId": "artist-36", "album": "Joy of Little Things", "duration": 210, "youtubeVideoId": "7y6t5r4e3w4", "genre": "Indie Folk", "mood": "Euphoric", "language": "English", "bpm": 108, "danceability": 0.75, "energy": 0.72, "valence": 0.85, "acousticness": 0.45, "vibeScore": 0.92 },
  { "title": "Joy of Little Things", "artist": "When Chai Met Toast", "artistId": "artist-36", "album": "Joy of Little Things", "duration": 224, "youtubeVideoId": "3w2q1a0s9d0", "genre": "Indie Folk", "mood": "Euphoric", "language": "English", "bpm": 112, "danceability": 0.78, "energy": 0.74, "valence": 0.88, "acousticness": 0.40, "vibeScore": 0.91 },
  { "title": "Believe", "artist": "When Chai Met Toast", "artistId": "artist-36", "album": "Believe", "duration": 198, "youtubeVideoId": "1j2k3l4m5n8", "genre": "Indie Folk", "mood": "Empowering", "language": "English", "bpm": 105, "danceability": 0.72, "energy": 0.70, "valence": 0.82, "acousticness": 0.42, "vibeScore": 0.90 },

  # Seedhe Maut & DIVINE
  { "title": "Namastute", "artist": "Seedhe Maut", "artistId": "artist-37", "album": "Nayaab", "duration": 194, "youtubeVideoId": "7u8i9o0p1q6", "genre": "Desi Hip Hop", "mood": "Energetic", "language": "Hindi", "bpm": 130, "danceability": 0.88, "energy": 0.95, "valence": 0.70, "acousticness": 0.05, "vibeScore": 0.95 },
  { "title": "101", "artist": "Seedhe Maut", "artistId": "artist-37", "album": "Nayaab", "duration": 204, "youtubeVideoId": "3e4r5t6y7u2", "genre": "Desi Hip Hop", "mood": "Energetic", "language": "Hindi", "bpm": 126, "danceability": 0.86, "energy": 0.92, "valence": 0.68, "acousticness": 0.08, "vibeScore": 0.94 },
  { "title": "Kohinoor", "artist": "DIVINE", "artistId": "artist-38", "album": "Kohinoor", "duration": 218, "youtubeVideoId": "8b9a0c1d2e4", "genre": "Gully Rap", "mood": "Empowering", "language": "Hindi", "bpm": 98, "danceability": 0.84, "energy": 0.88, "valence": 0.72, "acousticness": 0.10, "vibeScore": 0.95 },
  { "title": "Chal Bombay", "artist": "DIVINE", "artistId": "artist-38", "album": "Kohinoor", "duration": 185, "youtubeVideoId": "4f5g6h7j8k0", "genre": "Gully Rap", "mood": "Energetic", "language": "Hindi", "bpm": 104, "danceability": 0.89, "energy": 0.86, "valence": 0.82, "acousticness": 0.12, "vibeScore": 0.94 },
  { "title": "Mirchi", "artist": "DIVINE", "artistId": "artist-38", "album": "Punya Paap", "duration": 214, "youtubeVideoId": "0l1k2j3h4g6", "genre": "Gully Rap", "mood": "Energetic", "language": "Hindi", "bpm": 110, "danceability": 0.91, "energy": 0.90, "valence": 0.85, "acousticness": 0.08, "vibeScore": 0.95 },

  # South Indian & Regional (Tamil, Telugu, Malayalam, Marathi, Gujarati)
  # Anirudh Ravichander (Tamil)
  { "title": "Why This Kolaveri Di", "artist": "Anirudh Ravichander", "artistId": "artist-39", "album": "3", "duration": 245, "youtubeVideoId": "YR12Z8f1Dh8", "genre": "Tamil Pop", "mood": "Euphoric", "language": "Tamil", "bpm": 118, "danceability": 0.88, "energy": 0.86, "valence": 0.85, "acousticness": 0.15, "vibeScore": 0.97 },
  { "title": "Arabic Kuthu", "artist": "Anirudh Ravichander", "artistId": "artist-39", "album": "Beast", "duration": 279, "youtubeVideoId": "KUN5Uf9mObQ", "genre": "Tamil Pop", "mood": "Euphoric", "bpm": 128, "language": "Tamil", "danceability": 0.92, "energy": 0.96, "valence": 0.94, "acousticness": 0.06, "vibeScore": 0.98 },
  { "title": "Vaathi Coming", "artist": "Anirudh Ravichander", "artistId": "artist-39", "album": "Master", "duration": 230, "youtubeVideoId": "vx2u5uUu3DE", "genre": "Tamil Pop", "mood": "Energetic", "language": "Tamil", "bpm": 130, "danceability": 0.94, "energy": 0.97, "valence": 0.92, "acousticness": 0.05, "vibeScore": 0.98 },
  { "title": "Hukum", "artist": "Anirudh Ravichander", "artistId": "artist-39", "album": "Jailer", "duration": 204, "youtubeVideoId": "1F3hm6MfR1E", "genre": "Tamil Pop", "mood": "Empowering", "language": "Tamil", "bpm": 124, "danceability": 0.88, "energy": 0.98, "valence": 0.80, "acousticness": 0.04, "vibeScore": 0.97 },
  { "title": "Badass", "artist": "Anirudh Ravichander", "artistId": "artist-39", "album": "Leo", "duration": 229, "youtubeVideoId": "6m7n8b9v0c2", "genre": "Tamil Pop", "mood": "Energetic", "language": "Tamil", "bpm": 126, "danceability": 0.89, "energy": 0.96, "valence": 0.82, "acousticness": 0.06, "vibeScore": 0.96 },
  { "title": "Naa Ready", "artist": "Anirudh Ravichander", "artistId": "artist-39", "album": "Leo", "duration": 248, "youtubeVideoId": "2q3w4e5r6t1", "genre": "Tamil Pop", "mood": "Euphoric", "language": "Tamil", "bpm": 130, "danceability": 0.91, "energy": 0.95, "valence": 0.90, "acousticness": 0.05, "vibeScore": 0.96 },
  { "title": "Kaavaalaa", "artist": "Anirudh Ravichander", "artistId": "artist-39", "album": "Jailer", "duration": 190, "youtubeVideoId": "8y9u0i1o2p7", "genre": "Tamil Pop", "mood": "Euphoric", "language": "Tamil", "bpm": 122, "danceability": 0.92, "energy": 0.94, "valence": 0.95, "acousticness": 0.08, "vibeScore": 0.96 },

  # Sid Sriram & DSP (Telugu / Tamil)
  { "title": "Srivalli", "artist": "Sid Sriram", "artistId": "artist-40", "album": "Pushpa: The Rise", "duration": 224, "youtubeVideoId": "hcMzwMrr1tE", "genre": "Carnatic Fusion", "mood": "Romantic", "language": "Telugu", "bpm": 92, "danceability": 0.72, "energy": 0.68, "valence": 0.78, "acousticness": 0.35, "vibeScore": 0.97 },
  { "title": "Samajavaragamana", "artist": "Sid Sriram", "artistId": "artist-40", "album": "Ala Vaikunthapurramuloo", "duration": 224, "youtubeVideoId": "4a5s6d7f8g6", "genre": "Carnatic Fusion", "mood": "Romantic", "language": "Telugu", "bpm": 88, "danceability": 0.70, "energy": 0.65, "valence": 0.80, "acousticness": 0.40, "vibeScore": 0.96 },
  { "title": "Inkem Inkem", "artist": "Sid Sriram", "artistId": "artist-40", "album": "Geetha Govindam", "duration": 268, "youtubeVideoId": "0z1x2c3v4b9", "genre": "Carnatic Fusion", "mood": "Romantic", "language": "Telugu", "bpm": 86, "danceability": 0.68, "energy": 0.62, "valence": 0.76, "acousticness": 0.42, "vibeScore": 0.95 },
  { "title": "Kannaana Kanney", "artist": "Sid Sriram", "artistId": "artist-40", "album": "Viswasam", "duration": 269, "youtubeVideoId": "6n7m8k9j0h5", "genre": "Carnatic Fusion", "mood": "Romantic", "language": "Tamil", "bpm": 84, "danceability": 0.60, "energy": 0.58, "valence": 0.65, "acousticness": 0.55, "vibeScore": 0.96 },

  { "title": "Oo Antava", "artist": "Devi Sri Prasad (DSP)", "artistId": "artist-41", "album": "Pushpa: The Rise", "duration": 227, "youtubeVideoId": "1z2x3c4v5b9", "genre": "Telugu Pop", "mood": "Energetic", "language": "Telugu", "bpm": 105, "danceability": 0.90, "energy": 0.92, "valence": 0.85, "acousticness": 0.08, "vibeScore": 0.97 },
  { "title": "Saami Saami", "artist": "Devi Sri Prasad (DSP)", "artistId": "artist-41", "album": "Pushpa: The Rise", "duration": 223, "youtubeVideoId": "7n8m9k0j1h5", "genre": "Telugu Pop", "mood": "Euphoric", "language": "Telugu", "bpm": 120, "danceability": 0.91, "energy": 0.94, "valence": 0.92, "acousticness": 0.06, "vibeScore": 0.96 },
  { "title": "Butta Bomma", "artist": "Devi Sri Prasad (DSP)", "artistId": "artist-41", "album": "Ala Vaikunthapurramuloo", "duration": 198, "youtubeVideoId": "3q4w5e6r7t1", "genre": "Telugu Pop", "mood": "Euphoric", "language": "Telugu", "bpm": 115, "danceability": 0.88, "energy": 0.89, "valence": 0.93, "acousticness": 0.12, "vibeScore": 0.96 },

  # Sushin Shyam (Malayalam)
  { "title": "Illuminati", "artist": "Sushin Shyam", "artistId": "artist-42", "album": "Aavesham", "duration": 204, "youtubeVideoId": "tOM-nWPcR4U", "genre": "Malayalam Film Score", "mood": "Euphoric", "language": "Malayalam", "bpm": 125, "danceability": 0.92, "energy": 0.95, "valence": 0.90, "acousticness": 0.06, "vibeScore": 0.98 },
  { "title": "Kuthanthram", "artist": "Sushin Shyam", "artistId": "artist-42", "album": "Manjummel Boys", "duration": 178, "youtubeVideoId": "9u0i1o2p3q7", "genre": "Malayalam Film Score", "mood": "Empowering", "language": "Malayalam", "bpm": 118, "danceability": 0.86, "energy": 0.92, "valence": 0.82, "acousticness": 0.08, "vibeScore": 0.96 },
  { "title": "Aadharanjali", "artist": "Sushin Shyam", "artistId": "artist-42", "album": "Romancham", "duration": 192, "youtubeVideoId": "5a6s7d8f9g3", "genre": "Malayalam Film Score", "mood": "Energetic", "language": "Malayalam", "bpm": 122, "danceability": 0.89, "energy": 0.91, "valence": 0.88, "acousticness": 0.07, "vibeScore": 0.95 },

  # Ajay-Atul (Marathi)
  { "title": "Zingaat", "artist": "Ajay-Atul", "artistId": "artist-43", "album": "Sairat", "duration": 226, "youtubeVideoId": "8ZpZ_W_tX6E", "genre": "Marathi Film Score", "mood": "Euphoric", "language": "Marathi", "bpm": 136, "danceability": 0.95, "energy": 0.99, "valence": 0.98, "acousticness": 0.04, "vibeScore": 0.99 },
  { "title": "Sairat Zaala Ji", "artist": "Ajay-Atul", "artistId": "artist-43", "album": "Sairat", "duration": 369, "youtubeVideoId": "1h2j3k4l5m9", "genre": "Marathi Film Score", "mood": "Romantic", "language": "Marathi", "bpm": 86, "danceability": 0.62, "energy": 0.68, "valence": 0.72, "acousticness": 0.45, "vibeScore": 0.96 },
  { "title": "Yad Lagla", "artist": "Ajay-Atul", "artistId": "artist-43", "album": "Sairat", "duration": 314, "youtubeVideoId": "7z8x9c0v1b5", "genre": "Marathi Film Score", "mood": "Romantic", "language": "Marathi", "bpm": 80, "danceability": 0.58, "energy": 0.60, "valence": 0.64, "acousticness": 0.50, "vibeScore": 0.95 },

  # Sachin-Jigar (Gujarati / Hindi)
  { "title": "Khalasi", "artist": "Sachin-Jigar", "artistId": "artist-44", "album": "Coke Studio Bharat", "duration": 252, "youtubeVideoId": "q8x9w2e3r41", "genre": "Gujarati Pop", "mood": "Euphoric", "language": "Gujarati", "bpm": 118, "danceability": 0.91, "energy": 0.94, "valence": 0.96, "acousticness": 0.10, "vibeScore": 0.98 },
  { "title": "Radha Ne Shyam", "artist": "Sachin-Jigar", "artistId": "artist-44", "album": "Radha Ne Shyam", "duration": 268, "youtubeVideoId": "s1d2f3g4h51", "genre": "Gujarati Pop", "mood": "Euphoric", "language": "Gujarati", "bpm": 124, "danceability": 0.89, "energy": 0.92, "valence": 0.94, "acousticness": 0.12, "vibeScore": 0.95 },
  { "title": "Chand Ne Kaho", "artist": "Sachin-Jigar", "artistId": "artist-44", "album": "Chaal Jeevi Laiye!", "duration": 286, "youtubeVideoId": "x9c8v7b6n51", "genre": "Gujarati Pop", "mood": "Romantic", "language": "Gujarati", "bpm": 86, "danceability": 0.65, "energy": 0.58, "valence": 0.72, "acousticness": 0.52, "vibeScore": 0.94 }
]
