# scripts/catalog_data_western.py
# ~120 Verified Global Pop, Hip-Hop, Rock & EDM Tracks

WESTERN_TRACKS = [
  # The Weeknd
  { "title": "Blinding Lights", "artist": "The Weeknd", "artistId": "artist-45", "album": "After Hours", "duration": 200, "youtubeVideoId": "4NRXx6U8ABQ", "genre": "Synth-pop", "mood": "Euphoric", "bpm": 171, "danceability": 0.88, "energy": 0.90, "valence": 0.82, "acousticness": 0.08, "vibeScore": 0.99 },
  { "title": "Starboy", "artist": "The Weeknd", "artistId": "artist-45", "album": "Starboy", "duration": 230, "youtubeVideoId": "34Na4j8AVgA", "genre": "R&B", "mood": "Energetic", "bpm": 93, "danceability": 0.85, "energy": 0.84, "valence": 0.72, "acousticness": 0.12, "vibeScore": 0.98 },
  { "title": "Save Your Tears", "artist": "The Weeknd", "artistId": "artist-45", "album": "After Hours", "duration": 215, "youtubeVideoId": "XXYlFuWEuKI", "genre": "Synth-pop", "mood": "Romantic", "bpm": 118, "danceability": 0.82, "energy": 0.80, "valence": 0.76, "acousticness": 0.15, "vibeScore": 0.97 },
  { "title": "After Hours", "artist": "The Weeknd", "artistId": "artist-45", "album": "After Hours", "duration": 361, "youtubeVideoId": "ygTZZpVkm3o", "genre": "R&B", "mood": "Late Night", "bpm": 109, "danceability": 0.74, "energy": 0.72, "valence": 0.48, "acousticness": 0.22, "vibeScore": 0.96 },
  { "title": "Die For You", "artist": "The Weeknd", "artistId": "artist-45", "album": "Starboy", "duration": 260, "youtubeVideoId": "QLCpqdqeoII", "genre": "R&B", "mood": "Romantic", "bpm": 67, "danceability": 0.68, "energy": 0.62, "valence": 0.58, "acousticness": 0.28, "vibeScore": 0.96 },
  { "title": "The Hills", "artist": "The Weeknd", "artistId": "artist-45", "album": "Beauty Behind the Madness", "duration": 242, "youtubeVideoId": "yzTuBuRdAyA", "genre": "R&B", "mood": "Late Night", "bpm": 113, "danceability": 0.72, "energy": 0.78, "valence": 0.42, "acousticness": 0.16, "vibeScore": 0.97 },
  { "title": "Can't Feel My Face", "artist": "The Weeknd", "artistId": "artist-45", "album": "Beauty Behind the Madness", "duration": 213, "youtubeVideoId": "dqt8Z1k0oWQ", "genre": "Pop", "mood": "Euphoric", "bpm": 108, "danceability": 0.86, "energy": 0.88, "valence": 0.85, "acousticness": 0.10, "vibeScore": 0.96 },
  { "title": "I Feel It Coming", "artist": "The Weeknd", "artistId": "artist-45", "album": "Starboy", "duration": 269, "youtubeVideoId": "qFLhGq0060w", "genre": "Disco", "mood": "Romantic", "bpm": 93, "danceability": 0.80, "energy": 0.76, "valence": 0.84, "acousticness": 0.20, "vibeScore": 0.95 },

  # Drake
  { "title": "One Dance", "artist": "Drake", "artistId": "artist-46", "album": "Views", "duration": 174, "youtubeVideoId": "iAbnEUA0wpA", "genre": "Dancehall", "mood": "Chill", "bpm": 104, "danceability": 0.88, "energy": 0.78, "valence": 0.82, "acousticness": 0.14, "vibeScore": 0.98 },
  { "title": "God's Plan", "artist": "Drake", "artistId": "artist-46", "album": "Scorpion", "duration": 198, "youtubeVideoId": "xpVfcZ0ZcFM", "genre": "Hip-Hop", "mood": "Empowering", "bpm": 77, "danceability": 0.84, "energy": 0.65, "valence": 0.68, "acousticness": 0.18, "vibeScore": 0.97 },
  { "title": "Hotline Bling", "artist": "Drake", "artistId": "artist-46", "album": "Views", "duration": 267, "youtubeVideoId": "uxpDa-c-4Mc", "genre": "R&B", "mood": "Late Night", "bpm": 135, "danceability": 0.89, "energy": 0.62, "valence": 0.75, "acousticness": 0.22, "vibeScore": 0.96 },
  { "title": "In My Feelings", "artist": "Drake", "artistId": "artist-46", "album": "Scorpion", "duration": 217, "youtubeVideoId": "DRS_PpOrUZ4", "genre": "Hip-Hop", "mood": "Euphoric", "bpm": 91, "danceability": 0.86, "energy": 0.72, "valence": 0.84, "acousticness": 0.15, "vibeScore": 0.96 },
  { "title": "Passionfruit", "artist": "Drake", "artistId": "artist-46", "album": "More Life", "duration": 298, "youtubeVideoId": "8Xf_o3qFf4A", "genre": "R&B", "mood": "Chill", "bpm": 112, "danceability": 0.82, "energy": 0.58, "valence": 0.65, "acousticness": 0.32, "vibeScore": 0.95 },
  { "title": "Rich Flex", "artist": "Drake", "artistId": "artist-46", "album": "Her Loss", "duration": 239, "youtubeVideoId": "v8w8e7r6t52", "genre": "Trap", "mood": "Energetic", "bpm": 140, "danceability": 0.84, "energy": 0.86, "valence": 0.60, "acousticness": 0.08, "vibeScore": 0.94 },

  # Dua Lipa
  { "title": "Levitating", "artist": "Dua Lipa", "artistId": "artist-47", "album": "Future Nostalgia", "duration": 203, "youtubeVideoId": "TUVcZfQe-Kw", "genre": "Disco", "mood": "Euphoric", "bpm": 103, "danceability": 0.92, "energy": 0.92, "valence": 0.91, "acousticness": 0.07, "vibeScore": 0.98 },
  { "title": "Don't Start Now", "artist": "Dua Lipa", "artistId": "artist-47", "album": "Future Nostalgia", "duration": 183, "youtubeVideoId": "oygrmJFKYZY", "genre": "Disco", "mood": "Empowering", "bpm": 124, "danceability": 0.90, "energy": 0.90, "valence": 0.85, "acousticness": 0.08, "vibeScore": 0.97 },
  { "title": "New Rules", "artist": "Dua Lipa", "artistId": "artist-47", "album": "Dua Lipa", "duration": 209, "youtubeVideoId": "k2qgadSvNyU", "genre": "Dance-pop", "mood": "Empowering", "bpm": 116, "danceability": 0.88, "energy": 0.85, "valence": 0.78, "acousticness": 0.10, "vibeScore": 0.96 },
  { "title": "Break My Heart", "artist": "Dua Lipa", "artistId": "artist-47", "album": "Future Nostalgia", "duration": 221, "youtubeVideoId": "Nj2U6rhnucI", "genre": "Disco", "mood": "Energetic", "bpm": 113, "danceability": 0.87, "energy": 0.88, "valence": 0.84, "acousticness": 0.09, "vibeScore": 0.95 },
  { "title": "Dance The Night", "artist": "Dua Lipa", "artistId": "artist-47", "album": "Barbie The Album", "duration": 176, "youtubeVideoId": "OiC1rgCPmUQ", "genre": "Disco", "mood": "Euphoric", "bpm": 110, "danceability": 0.90, "energy": 0.91, "valence": 0.92, "acousticness": 0.06, "vibeScore": 0.96 },

  # Post Malone
  { "title": "Rockstar", "artist": "Post Malone", "artistId": "artist-48", "album": "Beerbongs & Bentleys", "duration": 218, "youtubeVideoId": "UceaB440jbw", "genre": "Trap", "mood": "Late Night", "bpm": 160, "danceability": 0.82, "energy": 0.76, "valence": 0.52, "acousticness": 0.18, "vibeScore": 0.98 },
  { "title": "Sunflower", "artist": "Post Malone", "artistId": "artist-48", "album": "Spider-Man: Into the Spider-Verse", "duration": 158, "youtubeVideoId": "ApXoWvfEYVU", "genre": "Pop", "mood": "Euphoric", "bpm": 90, "danceability": 0.86, "energy": 0.74, "valence": 0.92, "acousticness": 0.25, "vibeScore": 0.99 },
  { "title": "Circles", "artist": "Post Malone", "artistId": "artist-48", "album": "Hollywood's Bleeding", "duration": 215, "youtubeVideoId": "wXhTHyIgQ_U", "genre": "Pop Rock", "mood": "Chill", "bpm": 120, "danceability": 0.84, "energy": 0.78, "valence": 0.80, "acousticness": 0.28, "vibeScore": 0.97 },
  { "title": "Congratulations", "artist": "Post Malone", "artistId": "artist-48", "album": "Stoney", "duration": 220, "youtubeVideoId": "SC4xZwuaCwo", "genre": "Hip-Hop", "mood": "Empowering", "bpm": 123, "danceability": 0.85, "energy": 0.80, "valence": 0.75, "acousticness": 0.14, "vibeScore": 0.96 },
  { "title": "Better Now", "artist": "Post Malone", "artistId": "artist-48", "album": "Beerbongs & Bentleys", "duration": 231, "youtubeVideoId": "UYwF-jdcVjY", "genre": "Pop", "mood": "Late Night", "bpm": 145, "danceability": 0.80, "energy": 0.78, "valence": 0.65, "acousticness": 0.22, "vibeScore": 0.95 },

  # Billie Eilish
  { "title": "Bad Guy", "artist": "Billie Eilish", "artistId": "artist-49", "album": "When We All Fall Asleep, Where Do We Go?", "duration": 194, "youtubeVideoId": "DyDfgMOUjCI", "genre": "Electropop", "mood": "Energetic", "bpm": 135, "danceability": 0.92, "energy": 0.70, "valence": 0.65, "acousticness": 0.28, "vibeScore": 0.98 },
  { "title": "Lovely", "artist": "Billie Eilish", "artistId": "artist-49", "album": "13 Reasons Why", "duration": 200, "youtubeVideoId": "V1Pl8CzNzCw", "genre": "Alt Pop", "mood": "Late Night", "bpm": 115, "danceability": 0.58, "energy": 0.40, "valence": 0.25, "acousticness": 0.75, "vibeScore": 0.97 },
  { "title": "Everything I Wanted", "artist": "Billie Eilish", "artistId": "artist-49", "album": "Everything I Wanted", "duration": 245, "youtubeVideoId": "egVU289EYL8", "genre": "Alt Pop", "mood": "Chill", "bpm": 120, "danceability": 0.72, "energy": 0.45, "valence": 0.42, "acousticness": 0.68, "vibeScore": 0.96 },
  { "title": "Happier Than Ever", "artist": "Billie Eilish", "artistId": "artist-49", "album": "Happier Than Ever", "duration": 298, "youtubeVideoId": "5GJWxDKyk3A", "genre": "Alt Rock", "mood": "Empowering", "bpm": 80, "danceability": 0.55, "energy": 0.85, "valence": 0.48, "acousticness": 0.45, "vibeScore": 0.97 },
  { "title": "Birds of a Feather", "artist": "Billie Eilish", "artistId": "artist-49", "album": "Hit Me Hard and Soft", "duration": 196, "youtubeVideoId": "d5gf9dXb49o", "genre": "Alt Pop", "mood": "Romantic", "bpm": 105, "danceability": 0.78, "energy": 0.65, "valence": 0.75, "acousticness": 0.35, "vibeScore": 0.96 },

  # Travis Scott & Kendrick Lamar
  { "title": "SICKO MODE", "artist": "Travis Scott", "artistId": "artist-50", "album": "ASTROWORLD", "duration": 312, "youtubeVideoId": "6ONRf7h3sdk", "genre": "Trap", "mood": "Energetic", "bpm": 155, "danceability": 0.88, "energy": 0.94, "valence": 0.62, "acousticness": 0.05, "vibeScore": 0.99 },
  { "title": "Goosebumps", "artist": "Travis Scott", "artistId": "artist-50", "album": "Birds in the Trap Sing McKnight", "duration": 243, "youtubeVideoId": "Dst9gZkq1a8", "genre": "Trap", "mood": "Energetic", "bpm": 130, "danceability": 0.86, "energy": 0.88, "valence": 0.58, "acousticness": 0.08, "vibeScore": 0.98 },
  { "title": "HIGHEST IN THE ROOM", "artist": "Travis Scott", "artistId": "artist-50", "album": "HIGHEST IN THE ROOM", "duration": 176, "youtubeVideoId": "tfSS1e3kYeo", "genre": "Trap", "mood": "Late Night", "bpm": 154, "danceability": 0.82, "energy": 0.78, "valence": 0.45, "acousticness": 0.12, "vibeScore": 0.96 },
  { "title": "FE!N", "artist": "Travis Scott", "artistId": "artist-50", "album": "UTOPIA", "duration": 191, "youtubeVideoId": "B9synWjqBn8", "genre": "Trap", "mood": "Energetic", "bpm": 148, "danceability": 0.89, "energy": 0.96, "valence": 0.65, "acousticness": 0.04, "vibeScore": 0.97 },

  { "title": "HUMBLE.", "artist": "Kendrick Lamar", "artistId": "artist-51", "album": "DAMN.", "duration": 177, "youtubeVideoId": "tvTRZJ-4EyI", "genre": "West Coast Rap", "mood": "Energetic", "bpm": 150, "danceability": 0.90, "energy": 0.92, "valence": 0.78, "acousticness": 0.05, "vibeScore": 0.99 },
  { "title": "Money Trees", "artist": "Kendrick Lamar", "artistId": "artist-51", "album": "good kid, m.A.A.d city", "duration": 386, "youtubeVideoId": "smqhSl0u_Qk", "genre": "West Coast Rap", "mood": "Chill", "bpm": 72, "danceability": 0.78, "energy": 0.62, "valence": 0.55, "acousticness": 0.25, "vibeScore": 0.97 },
  { "title": "Not Like Us", "artist": "Kendrick Lamar", "artistId": "artist-51", "album": "Not Like Us", "duration": 274, "youtubeVideoId": "H58vbez_m4E", "genre": "West Coast Rap", "mood": "Empowering", "bpm": 101, "danceability": 0.92, "energy": 0.94, "valence": 0.88, "acousticness": 0.06, "vibeScore": 0.99 },

  # Harry Styles & Taylor Swift
  { "title": "As It Was", "artist": "Harry Styles", "artistId": "artist-52", "album": "Harry's House", "duration": 167, "youtubeVideoId": "H5v3k2q3w4e", "genre": "Synth-pop", "mood": "Euphoric", "bpm": 174, "danceability": 0.85, "energy": 0.88, "valence": 0.90, "acousticness": 0.15, "vibeScore": 0.98 },
  { "title": "Watermelon Sugar", "artist": "Harry Styles", "artistId": "artist-52", "album": "Fine Line", "duration": 174, "youtubeVideoId": "E07s5ZYygMg", "genre": "Pop", "mood": "Euphoric", "bpm": 95, "danceability": 0.80, "energy": 0.82, "valence": 0.86, "acousticness": 0.18, "vibeScore": 0.97 },
  { "title": "Adore You", "artist": "Harry Styles", "artistId": "artist-52", "album": "Fine Line", "duration": 207, "youtubeVideoId": "VF-r5TtlT9w", "genre": "Pop", "mood": "Romantic", "bpm": 99, "danceability": 0.78, "energy": 0.76, "valence": 0.82, "acousticness": 0.20, "vibeScore": 0.95 },

  { "title": "Cruel Summer", "artist": "Taylor Swift", "artistId": "artist-53", "album": "Lover", "duration": 178, "youtubeVideoId": "ic8j13U_FS8", "genre": "Pop", "mood": "Euphoric", "bpm": 170, "danceability": 0.86, "energy": 0.92, "valence": 0.88, "acousticness": 0.10, "vibeScore": 0.99 },
  { "title": "Anti-Hero", "artist": "Taylor Swift", "artistId": "artist-53", "album": "Midnights", "duration": 200, "youtubeVideoId": "b1kbLwvqugk", "genre": "Synth-pop", "mood": "Late Night", "bpm": 97, "danceability": 0.78, "energy": 0.72, "valence": 0.65, "acousticness": 0.22, "vibeScore": 0.97 },
  { "title": "Blank Space", "artist": "Taylor Swift", "artistId": "artist-53", "album": "1989", "duration": 231, "youtubeVideoId": "e-ORhEE9VVg", "genre": "Pop", "mood": "Energetic", "bpm": 96, "danceability": 0.82, "energy": 0.80, "valence": 0.78, "acousticness": 0.12, "vibeScore": 0.97 },
  { "title": "Shake It Off", "artist": "Taylor Swift", "artistId": "artist-53", "album": "1989", "duration": 219, "youtubeVideoId": "nfWlot6h_JM", "genre": "Pop", "mood": "Euphoric", "bpm": 160, "danceability": 0.89, "energy": 0.94, "valence": 0.95, "acousticness": 0.06, "vibeScore": 0.98 },
  { "title": "Love Story", "artist": "Taylor Swift", "artistId": "artist-53", "album": "Fearless", "duration": 235, "youtubeVideoId": "8xg3vE8Ie_E", "genre": "Country Pop", "mood": "Romantic", "bpm": 119, "danceability": 0.74, "energy": 0.78, "valence": 0.82, "acousticness": 0.28, "vibeScore": 0.96 },

  # Ed Sheeran & Bruno Mars
  { "title": "Shape of You", "artist": "Ed Sheeran", "artistId": "artist-54", "album": "÷ (Divide)", "duration": 233, "youtubeVideoId": "JGwWNGJdvx8", "genre": "Pop", "mood": "Euphoric", "bpm": 96, "danceability": 0.92, "energy": 0.85, "valence": 0.93, "acousticness": 0.15, "vibeScore": 0.99 },
  { "title": "Perfect", "artist": "Ed Sheeran", "artistId": "artist-54", "album": "÷ (Divide)", "duration": 263, "youtubeVideoId": "2Vv-BfVoq4c", "genre": "Acoustic", "mood": "Romantic", "bpm": 95, "danceability": 0.65, "energy": 0.52, "valence": 0.68, "acousticness": 0.62, "vibeScore": 0.98 },
  { "title": "Thinking Out Loud", "artist": "Ed Sheeran", "artistId": "artist-54", "album": "x (Multiply)", "duration": 281, "youtubeVideoId": "lp-EO5I60KA", "genre": "Acoustic", "mood": "Romantic", "bpm": 79, "danceability": 0.68, "energy": 0.54, "valence": 0.72, "acousticness": 0.58, "vibeScore": 0.97 },
  { "title": "Bad Habits", "artist": "Ed Sheeran", "artistId": "artist-54", "album": "= (Equals)", "duration": 231, "youtubeVideoId": "orJSJGHjBLI", "genre": "Dance-pop", "mood": "Energetic", "bpm": 126, "danceability": 0.88, "energy": 0.90, "valence": 0.85, "acousticness": 0.08, "vibeScore": 0.96 },

  { "title": "Uptown Funk", "artist": "Bruno Mars", "artistId": "artist-55", "album": "Uptown Special", "duration": 270, "youtubeVideoId": "OPf0YbXqDm0", "genre": "Funk", "mood": "Euphoric", "bpm": 115, "danceability": 0.94, "energy": 0.96, "valence": 0.96, "acousticness": 0.04, "vibeScore": 0.99 },
  { "title": "24K Magic", "artist": "Bruno Mars", "artistId": "artist-55", "album": "24K Magic", "duration": 226, "youtubeVideoId": "UqyT8IEBkvY", "genre": "Funk", "mood": "Euphoric", "bpm": 107, "danceability": 0.91, "energy": 0.92, "valence": 0.92, "acousticness": 0.07, "vibeScore": 0.98 },
  { "title": "That's What I Like", "artist": "Bruno Mars", "artistId": "artist-55", "album": "24K Magic", "duration": 206, "youtubeVideoId": "PMivT7MJ41M", "genre": "R&B", "mood": "Romantic", "bpm": 134, "danceability": 0.89, "energy": 0.78, "valence": 0.88, "acousticness": 0.12, "vibeScore": 0.97 },

  # Ariana Grande, SZA, Justin Bieber, Rihanna
  { "title": "7 Rings", "artist": "Ariana Grande", "artistId": "artist-56", "album": "Thank U, Next", "duration": 178, "youtubeVideoId": "QYh6mYIJG2Y", "genre": "Trap Pop", "mood": "Empowering", "bpm": 140, "danceability": 0.90, "energy": 0.80, "valence": 0.75, "acousticness": 0.14, "vibeScore": 0.97 },
  { "title": "Thank U Next", "artist": "Ariana Grande", "artistId": "artist-56", "album": "Thank U, Next", "duration": 207, "youtubeVideoId": "gl1aHhXnN1k", "genre": "Pop", "mood": "Empowering", "bpm": 107, "danceability": 0.85, "energy": 0.75, "valence": 0.82, "acousticness": 0.18, "vibeScore": 0.97 },
  { "title": "Kill Bill", "artist": "SZA", "artistId": "artist-57", "album": "SOS", "duration": 153, "youtubeVideoId": "mN_FkZ8G7h1", "genre": "R&B", "mood": "Late Night", "bpm": 118, "danceability": 0.84, "energy": 0.68, "valence": 0.65, "acousticness": 0.28, "vibeScore": 0.97 },
  { "title": "Snooze", "artist": "SZA", "artistId": "artist-57", "album": "SOS", "duration": 201, "youtubeVideoId": "5uWpYn7eZl9", "genre": "R&B", "mood": "Romantic", "bpm": 143, "danceability": 0.76, "energy": 0.62, "valence": 0.60, "acousticness": 0.35, "vibeScore": 0.96 },

  { "title": "Peaches", "artist": "Justin Bieber", "artistId": "artist-58", "album": "Justice", "duration": 198, "youtubeVideoId": "tQ0yjYUFKAE", "genre": "Pop", "mood": "Chill", "bpm": 90, "danceability": 0.85, "energy": 0.72, "valence": 0.82, "acousticness": 0.20, "vibeScore": 0.96 },
  { "title": "Stay", "artist": "Justin Bieber", "artistId": "artist-58", "album": "F*CK LOVE 3", "duration": 141, "youtubeVideoId": "kTJczUoc268", "genre": "Pop Rock", "mood": "Euphoric", "bpm": 170, "danceability": 0.88, "energy": 0.92, "valence": 0.86, "acousticness": 0.08, "vibeScore": 0.98 },
  { "title": "Umbrella", "artist": "Rihanna", "artistId": "artist-59", "album": "Good Girl Gone Bad", "duration": 275, "youtubeVideoId": "CvBfHwUxHIk", "genre": "Pop", "mood": "Empowering", "bpm": 87, "danceability": 0.86, "energy": 0.88, "valence": 0.80, "acousticness": 0.10, "vibeScore": 0.98 },
  { "title": "We Found Love", "artist": "Rihanna", "artistId": "artist-59", "album": "Talk That Talk", "duration": 215, "youtubeVideoId": "tg00YEETFzg", "genre": "EDM", "mood": "Euphoric", "bpm": 128, "danceability": 0.92, "energy": 0.96, "valence": 0.90, "acousticness": 0.05, "vibeScore": 0.99 },

  # Rock, Classics & EDM
  { "title": "Viva La Vida", "artist": "Coldplay", "artistId": "artist-60", "album": "Viva La Vida or Death and All His Friends", "duration": 242, "youtubeVideoId": "dvgZkm1xWPE", "genre": "Alt Rock", "mood": "Euphoric", "bpm": 138, "danceability": 0.78, "energy": 0.88, "valence": 0.82, "acousticness": 0.15, "vibeScore": 0.99 },
  { "title": "Yellow", "artist": "Coldplay", "artistId": "artist-60", "album": "Parachutes", "duration": 269, "youtubeVideoId": "yKNxeF4KMsY", "genre": "Alt Rock", "mood": "Romantic", "bpm": 87, "danceability": 0.60, "energy": 0.70, "valence": 0.65, "acousticness": 0.40, "vibeScore": 0.98 },
  { "title": "Fix You", "artist": "Coldplay", "artistId": "artist-60", "album": "X&Y", "duration": 295, "youtubeVideoId": "k4V3Mo61fJM", "genre": "Alt Rock", "mood": "Nostalgic", "bpm": 138, "danceability": 0.52, "energy": 0.68, "valence": 0.45, "acousticness": 0.55, "vibeScore": 0.99 },
  { "title": "Hymn for the Weekend", "artist": "Coldplay", "artistId": "artist-60", "album": "A Head Full of Dreams", "duration": 258, "youtubeVideoId": "YykjpeuMNEk", "genre": "Pop Rock", "mood": "Euphoric", "bpm": 90, "danceability": 0.82, "energy": 0.86, "valence": 0.88, "acousticness": 0.18, "vibeScore": 0.97 },

  { "title": "Bohemian Rhapsody", "artist": "Queen", "artistId": "artist-61", "album": "A Night at the Opera", "duration": 354, "youtubeVideoId": "fJ9rUzIMcZQ", "genre": "Classic Rock", "mood": "Empowering", "bpm": 72, "danceability": 0.55, "energy": 0.85, "valence": 0.60, "acousticness": 0.45, "vibeScore": 0.99 },
  { "title": "Don't Stop Me Now", "artist": "Queen", "artistId": "artist-61", "album": "Jazz", "duration": 209, "youtubeVideoId": "HgzGwKwLmgM", "genre": "Classic Rock", "mood": "Euphoric", "bpm": 156, "danceability": 0.85, "energy": 0.94, "valence": 0.96, "acousticness": 0.12, "vibeScore": 0.99 },

  { "title": "Do I Wanna Know?", "artist": "Arctic Monkeys", "artistId": "artist-62", "album": "AM", "duration": 272, "youtubeVideoId": "bpOSxM0rNPM", "genre": "Indie Rock", "mood": "Late Night", "bpm": 85, "danceability": 0.78, "energy": 0.82, "valence": 0.55, "acousticness": 0.18, "vibeScore": 0.98 },
  { "title": "505", "artist": "Arctic Monkeys", "artistId": "artist-62", "album": "Favourite Worst Nightmare", "duration": 253, "youtubeVideoId": "qU9mHegkTc4", "genre": "Indie Rock", "mood": "Late Night", "bpm": 140, "danceability": 0.65, "energy": 0.85, "valence": 0.45, "acousticness": 0.25, "vibeScore": 0.97 },

  { "title": "In The End", "artist": "Linkin Park", "artistId": "artist-63", "album": "Hybrid Theory", "duration": 216, "youtubeVideoId": "eVTXPUF4Oz4", "genre": "Nu Metal", "mood": "Empowering", "bpm": 105, "danceability": 0.75, "energy": 0.92, "valence": 0.58, "acousticness": 0.10, "vibeScore": 0.99 },
  { "title": "Numb", "artist": "Linkin Park", "artistId": "artist-63", "album": "Meteora", "duration": 187, "youtubeVideoId": "kXYiU_JCYtU", "genre": "Nu Metal", "mood": "Empowering", "bpm": 110, "danceability": 0.72, "energy": 0.94, "valence": 0.52, "acousticness": 0.08, "vibeScore": 0.99 },

  { "title": "Wake Me Up", "artist": "Avicii", "artistId": "artist-64", "album": "True", "duration": 249, "youtubeVideoId": "IcrbM1l_BoI", "genre": "EDM", "mood": "Euphoric", "bpm": 124, "danceability": 0.88, "energy": 0.96, "valence": 0.92, "acousticness": 0.15, "vibeScore": 0.99 },
  { "title": "The Nights", "artist": "Avicii", "artistId": "artist-64", "album": "The Days / Nights EP", "duration": 176, "youtubeVideoId": "UtF6Jej8yb4", "genre": "EDM", "mood": "Euphoric", "bpm": 126, "danceability": 0.89, "energy": 0.95, "valence": 0.94, "acousticness": 0.12, "vibeScore": 0.98 },
  { "title": "Levels", "artist": "Avicii", "artistId": "artist-64", "album": "Levels", "duration": 199, "youtubeVideoId": "_ovdm2yX4MA", "genre": "EDM", "mood": "Euphoric", "bpm": 126, "danceability": 0.90, "energy": 0.97, "valence": 0.91, "acousticness": 0.05, "vibeScore": 0.99 },

  { "title": "Closer", "artist": "The Chainsmokers", "artistId": "artist-65", "album": "Collage", "duration": 245, "youtubeVideoId": "PT2_F-1esPk", "genre": "EDM Pop", "mood": "Euphoric", "bpm": 95, "danceability": 0.88, "energy": 0.82, "valence": 0.86, "acousticness": 0.20, "vibeScore": 0.98 },
  { "title": "Paris", "artist": "The Chainsmokers", "artistId": "artist-65", "album": "Memories...Do Not Open", "duration": 221, "youtubeVideoId": "fRNkTS44hPN", "genre": "EDM Pop", "mood": "Chill", "bpm": 100, "danceability": 0.82, "energy": 0.74, "valence": 0.78, "acousticness": 0.25, "vibeScore": 0.96 },

  { "title": "Summer", "artist": "Calvin Harris", "artistId": "artist-66", "album": "Motion", "duration": 222, "youtubeVideoId": "ebXbLfLAC3r", "genre": "EDM", "mood": "Euphoric", "bpm": 128, "danceability": 0.92, "energy": 0.96, "valence": 0.92, "acousticness": 0.06, "vibeScore": 0.99 },
  { "title": "Feel So Close", "artist": "Calvin Harris", "artistId": "artist-66", "album": "18 Months", "duration": 206, "youtubeVideoId": "dGghkjpNhQ8", "genre": "EDM", "mood": "Euphoric", "bpm": 128, "danceability": 0.91, "energy": 0.95, "valence": 0.93, "acousticness": 0.07, "vibeScore": 0.98 },

  { "title": "Animals", "artist": "Martin Garrix", "artistId": "artist-67", "album": "Animals", "duration": 184, "youtubeVideoId": "gCYcHz2k5x0", "genre": "Big Room House", "mood": "Energetic", "bpm": 128, "danceability": 0.90, "energy": 0.98, "valence": 0.80, "acousticness": 0.02, "vibeScore": 0.98 }
]
