# scripts/catalog_data_bollywood.py
# ~120 Verified Bollywood & Hindi Tracks

BOLLYWOOD_TRACKS = [
  # Arijit Singh
  { "title": "Tum Hi Ho", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Aashiqui 2", "duration": 262, "youtubeVideoId": "IJq0yyWug1k", "genre": "Romantic", "mood": "Romantic", "bpm": 88, "danceability": 0.58, "energy": 0.55, "valence": 0.42, "acousticness": 0.48, "vibeScore": 0.98 },
  { "title": "Channa Mereya", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Ae Dil Hai Mushkil", "duration": 289, "youtubeVideoId": "284Ov7ysmfA", "genre": "Sufi", "mood": "Late Night", "bpm": 80, "danceability": 0.52, "energy": 0.58, "valence": 0.35, "acousticness": 0.54, "vibeScore": 0.97 },
  { "title": "Kesariya", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Brahmāstra", "duration": 268, "youtubeVideoId": "BddP6PYo2gs", "genre": "Romantic", "mood": "Romantic", "bpm": 92, "danceability": 0.65, "energy": 0.68, "valence": 0.72, "acousticness": 0.30, "vibeScore": 0.96 },
  { "title": "Apna Bana Le", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Bhediya", "duration": 261, "youtubeVideoId": "ElZfdU54Cp8", "genre": "Romantic", "mood": "Romantic", "bpm": 86, "danceability": 0.64, "energy": 0.60, "valence": 0.66, "acousticness": 0.38, "vibeScore": 0.95 },
  { "title": "Tere Hawale", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Laal Singh Chaddha", "duration": 346, "youtubeVideoId": "KUpwupYj_tY", "genre": "Romantic", "mood": "Romantic", "bpm": 84, "danceability": 0.55, "energy": 0.50, "valence": 0.48, "acousticness": 0.52, "vibeScore": 0.94 },
  { "title": "Phir Le Aya Dil", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Barfi!", "duration": 305, "youtubeVideoId": "0q_4mFq9w1k", "genre": "Ghazal", "mood": "Late Night", "bpm": 74, "danceability": 0.45, "energy": 0.38, "valence": 0.30, "acousticness": 0.78, "vibeScore": 0.93 },
  { "title": "Gerua", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Dilwale", "duration": 345, "youtubeVideoId": "AEIVhBS6baE", "genre": "Romantic", "mood": "Euphoric", "bpm": 90, "danceability": 0.62, "energy": 0.72, "valence": 0.65, "acousticness": 0.32, "vibeScore": 0.94 },
  { "title": "Kabira", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Yeh Jawaani Hai Deewani", "duration": 251, "youtubeVideoId": "jHNNMj5bNQw", "genre": "Folk", "mood": "Nostalgic", "bpm": 82, "danceability": 0.60, "energy": 0.52, "valence": 0.55, "acousticness": 0.62, "vibeScore": 0.96 },
  { "title": "Ilahi", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Yeh Jawaani Hai Deewani", "duration": 229, "youtubeVideoId": "fdubeMFwuGs", "genre": "Pop", "mood": "Euphoric", "bpm": 115, "danceability": 0.75, "energy": 0.85, "valence": 0.82, "acousticness": 0.18, "vibeScore": 0.93 },
  { "title": "Tera Yaar Hoon Main", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Sonu Ke Titu Ki Sweety", "duration": 299, "youtubeVideoId": "EatzcaVJRMs", "genre": "Bollywood", "mood": "Nostalgic", "bpm": 80, "danceability": 0.58, "energy": 0.56, "valence": 0.50, "acousticness": 0.45, "vibeScore": 0.95 },
  { "title": "O Bedardeya", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Tu Jhoothi Main Makkaar", "duration": 313, "youtubeVideoId": "1m2n3b4v5c6", "genre": "Romantic", "mood": "Late Night", "bpm": 78, "danceability": 0.50, "energy": 0.52, "valence": 0.34, "acousticness": 0.60, "vibeScore": 0.93 },
  { "title": "Tum Kya Mile", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Rocky Aur Rani Kii Prem Kahaani", "duration": 277, "youtubeVideoId": "7u8i9o0p1q3", "genre": "Romantic", "mood": "Romantic", "bpm": 94, "danceability": 0.68, "energy": 0.70, "valence": 0.75, "acousticness": 0.28, "vibeScore": 0.92 },
  { "title": "Satranga", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Animal", "duration": 271, "youtubeVideoId": "3e4r5t6y7u9", "genre": "Romantic", "mood": "Late Night", "bpm": 82, "danceability": 0.56, "energy": 0.62, "valence": 0.44, "acousticness": 0.48, "vibeScore": 0.94 },
  { "title": "Chaleya", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Jawan", "duration": 200, "youtubeVideoId": "9o8i7u6y5t5", "genre": "Pop", "mood": "Romantic", "bpm": 102, "danceability": 0.82, "energy": 0.78, "valence": 0.85, "acousticness": 0.16, "vibeScore": 0.95 },
  { "title": "Heeriye", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Heeriye", "duration": 194, "youtubeVideoId": "5r4e3w2q1a1", "genre": "Pop", "mood": "Romantic", "bpm": 96, "danceability": 0.78, "energy": 0.72, "valence": 0.80, "acousticness": 0.24, "vibeScore": 0.93 },
  { "title": "Shayad", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Love Aaj Kal", "duration": 247, "youtubeVideoId": "1a2s3d4f5g7", "genre": "Romantic", "mood": "Romantic", "bpm": 85, "danceability": 0.62, "energy": 0.58, "valence": 0.60, "acousticness": 0.42, "vibeScore": 0.92 },
  { "title": "Agar Tum Saath Ho", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Tamasha", "duration": 341, "youtubeVideoId": "7h8j9k0l1m3", "genre": "Romantic", "mood": "Late Night", "bpm": 82, "danceability": 0.54, "energy": 0.54, "valence": 0.38, "acousticness": 0.65, "vibeScore": 0.98 },
  { "title": "Hawayein", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Jab Harry Met Sejal", "duration": 290, "youtubeVideoId": "3l4m5n6o7p9", "genre": "Romantic", "mood": "Romantic", "bpm": 90, "danceability": 0.66, "energy": 0.64, "valence": 0.70, "acousticness": 0.35, "vibeScore": 0.94 },
  { "title": "Ae Dil Hai Mushkil", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Ae Dil Hai Mushkil", "duration": 269, "youtubeVideoId": "9q8w7e6r5t5", "genre": "Sufi", "mood": "Late Night", "bpm": 86, "danceability": 0.58, "energy": 0.65, "valence": 0.46, "acousticness": 0.45, "vibeScore": 0.96 },
  { "title": "Zaalima", "artist": "Arijit Singh", "artistId": "artist-20", "album": "Raees", "duration": 299, "youtubeVideoId": "2y3u4i5o6p8", "genre": "Romantic", "mood": "Romantic", "bpm": 92, "danceability": 0.72, "energy": 0.68, "valence": 0.76, "acousticness": 0.30, "vibeScore": 0.92 },

  # A.R. Rahman
  { "title": "Kun Faya Kun", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Rockstar", "duration": 473, "youtubeVideoId": "T94PHkuydcw", "genre": "Sufi", "mood": "Chill", "bpm": 76, "danceability": 0.48, "energy": 0.50, "valence": 0.52, "acousticness": 0.70, "vibeScore": 0.99 },
  { "title": "Jai Ho", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Slumdog Millionaire", "duration": 319, "youtubeVideoId": "xwwAVRyNmgQ", "genre": "World", "mood": "Euphoric", "bpm": 128, "danceability": 0.82, "energy": 0.92, "valence": 0.90, "acousticness": 0.08, "vibeScore": 0.98 },
  { "title": "Chaiyya Chaiyya", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Dil Se..", "duration": 395, "youtubeVideoId": "YOYN9qNXmAw", "genre": "Soundtrack", "mood": "Energetic", "bpm": 120, "danceability": 0.86, "energy": 0.94, "valence": 0.92, "acousticness": 0.09, "vibeScore": 0.99 },
  { "title": "Tere Bina", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Guru", "duration": 304, "youtubeVideoId": "8a9s0d1f2g4", "genre": "Sufi", "mood": "Romantic", "bpm": 80, "danceability": 0.60, "energy": 0.55, "valence": 0.62, "acousticness": 0.58, "vibeScore": 0.96 },
  { "title": "Masakali", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Delhi-6", "duration": 290, "youtubeVideoId": "4h5j6k7l8m0", "genre": "Pop", "mood": "Euphoric", "bpm": 105, "danceability": 0.80, "energy": 0.78, "valence": 0.88, "acousticness": 0.25, "vibeScore": 0.95 },
  { "title": "Rehna Tu", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Delhi-6", "duration": 411, "youtubeVideoId": "0z1x2c3v4b6", "genre": "Soul", "mood": "Chill", "bpm": 78, "danceability": 0.52, "energy": 0.48, "valence": 0.45, "acousticness": 0.68, "vibeScore": 0.94 },
  { "title": "Urvashi Urvashi", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Humse Hai Muqabla", "duration": 339, "youtubeVideoId": "6n7m8k9j0h2", "genre": "Dance", "mood": "Energetic", "bpm": 125, "danceability": 0.90, "energy": 0.92, "valence": 0.94, "acousticness": 0.06, "vibeScore": 0.97 },
  { "title": "Tu Hi Re", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Bombay", "duration": 434, "youtubeVideoId": "2w3e4r5t6y8", "genre": "Soundtrack", "mood": "Romantic", "bpm": 75, "danceability": 0.45, "energy": 0.42, "valence": 0.38, "acousticness": 0.72, "vibeScore": 0.96 },
  { "title": "Dil Se Re", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Dil Se..", "duration": 414, "youtubeVideoId": "8u9i0o1p2q4", "genre": "Soundtrack", "mood": "Empowering", "bpm": 88, "danceability": 0.65, "energy": 0.75, "valence": 0.58, "acousticness": 0.40, "vibeScore": 0.97 },
  { "title": "Khwaja Mere Khwaja", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Jodhaa Akbar", "duration": 418, "youtubeVideoId": "4a5s6d7f8g1", "genre": "Sufi", "mood": "Chill", "bpm": 74, "danceability": 0.46, "energy": 0.52, "valence": 0.50, "acousticness": 0.75, "vibeScore": 0.98 },
  { "title": "Jashn-E-Bahaaraa", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Jodhaa Akbar", "duration": 315, "youtubeVideoId": "0h1j2k3l4m6", "genre": "Romantic", "mood": "Romantic", "bpm": 84, "danceability": 0.62, "energy": 0.54, "valence": 0.65, "acousticness": 0.55, "vibeScore": 0.95 },
  { "title": "Rang De Basanti", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Rang De Basanti", "duration": 363, "youtubeVideoId": "6n7b8v9c0x2", "genre": "Bhangra", "mood": "Euphoric", "bpm": 126, "danceability": 0.88, "energy": 0.95, "valence": 0.92, "acousticness": 0.08, "vibeScore": 0.98 },
  { "title": "Matargashti", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Tamasha", "duration": 328, "youtubeVideoId": "2q3w4e5r6t8", "genre": "Pop", "mood": "Euphoric", "bpm": 112, "danceability": 0.82, "energy": 0.86, "valence": 0.90, "acousticness": 0.15, "vibeScore": 0.95 },
  { "title": "Enna Sona", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "OK Jaanu", "duration": 213, "youtubeVideoId": "8y9u0i1o2p4", "genre": "Romantic", "mood": "Romantic", "bpm": 88, "danceability": 0.68, "energy": 0.60, "valence": 0.74, "acousticness": 0.38, "vibeScore": 0.93 },
  { "title": "Param Sundari", "artist": "A.R. Rahman", "artistId": "artist-21", "album": "Mimi", "duration": 200, "youtubeVideoId": "4a5s6d7f8g2", "genre": "Dance", "mood": "Energetic", "bpm": 122, "danceability": 0.88, "energy": 0.90, "valence": 0.88, "acousticness": 0.10, "vibeScore": 0.94 },

  # Pritam
  { "title": "Badtameez Dil", "artist": "Pritam", "artistId": "artist-22", "album": "Yeh Jawaani Hai Deewani", "duration": 252, "youtubeVideoId": "II2EO3NwUr8", "genre": "Dance", "mood": "Euphoric", "bpm": 130, "danceability": 0.91, "energy": 0.96, "valence": 0.94, "acousticness": 0.05, "vibeScore": 0.98 },
  { "title": "Subhanallah", "artist": "Pritam", "artistId": "artist-22", "album": "Yeh Jawaani Hai Deewani", "duration": 249, "youtubeVideoId": "1z2x3c4v5b7", "genre": "Romantic", "mood": "Romantic", "bpm": 90, "danceability": 0.70, "energy": 0.62, "valence": 0.78, "acousticness": 0.32, "vibeScore": 0.92 },
  { "title": "Dilliwaali Girlfriend", "artist": "Pritam", "artistId": "artist-22", "album": "Yeh Jawaani Hai Deewani", "duration": 260, "youtubeVideoId": "7n8m9k0j1h3", "genre": "Dance", "mood": "Energetic", "bpm": 124, "danceability": 0.89, "energy": 0.93, "valence": 0.90, "acousticness": 0.08, "vibeScore": 0.94 },
  { "title": "Balam Pichkari", "artist": "Pritam", "artistId": "artist-22", "album": "Yeh Jawaani Hai Deewani", "duration": 289, "youtubeVideoId": "3q4w5e6r7t9", "genre": "Folk", "mood": "Euphoric", "bpm": 128, "danceability": 0.92, "energy": 0.95, "valence": 0.96, "acousticness": 0.07, "vibeScore": 0.97 },
  { "title": "Tum Se Hi", "artist": "Pritam", "artistId": "artist-22", "album": "Jab We Met", "duration": 321, "youtubeVideoId": "9u0i1o2p3q5", "genre": "Romantic", "mood": "Romantic", "bpm": 86, "danceability": 0.64, "energy": 0.58, "valence": 0.68, "acousticness": 0.44, "vibeScore": 0.96 },
  { "title": "Pee Loon", "artist": "Pritam", "artistId": "artist-22", "album": "Once Upon a Time in Mumbaai", "duration": 288, "youtubeVideoId": "5a6s7d8f9g1", "genre": "Sufi", "mood": "Romantic", "bpm": 84, "danceability": 0.66, "energy": 0.64, "valence": 0.72, "acousticness": 0.40, "vibeScore": 0.95 },
  { "title": "Mauja Hi Mauja", "artist": "Pritam", "artistId": "artist-22", "album": "Jab We Met", "duration": 244, "youtubeVideoId": "1h2j3k4l5m7", "genre": "Bhangra", "mood": "Euphoric", "bpm": 132, "danceability": 0.90, "energy": 0.96, "valence": 0.95, "acousticness": 0.06, "vibeScore": 0.97 },

  # Mohit Chauhan
  { "title": "Tum Ho", "artist": "Mohit Chauhan", "artistId": "artist-23", "album": "Rockstar", "duration": 319, "youtubeVideoId": "gkCKZuG4560", "genre": "Romantic", "mood": "Romantic", "bpm": 82, "danceability": 0.56, "energy": 0.52, "valence": 0.45, "acousticness": 0.62, "vibeScore": 0.97 },
  { "title": "Nadaan Parinde", "artist": "Mohit Chauhan", "artistId": "artist-23", "album": "Rockstar", "duration": 386, "youtubeVideoId": "ttTXST36tCQ", "genre": "Rock", "mood": "Empowering", "bpm": 92, "danceability": 0.58, "energy": 0.85, "valence": 0.50, "acousticness": 0.32, "vibeScore": 0.98 },
  { "title": "Phir Se Ud Chala", "artist": "Mohit Chauhan", "artistId": "artist-23", "album": "Rockstar", "duration": 271, "youtubeVideoId": "2Vv-BfVoq4g", "genre": "Acoustic", "mood": "Chill", "bpm": 90, "danceability": 0.65, "energy": 0.60, "valence": 0.70, "acousticness": 0.50, "vibeScore": 0.96 },
  { "title": "Saada Haq", "artist": "Mohit Chauhan", "artistId": "artist-23", "album": "Rockstar", "duration": 365, "youtubeVideoId": "7z8x9c0v1b3", "genre": "Rock", "mood": "Empowering", "bpm": 120, "danceability": 0.65, "energy": 0.92, "valence": 0.60, "acousticness": 0.12, "vibeScore": 0.97 },
  { "title": "Tujhe Bhula Diya", "artist": "Mohit Chauhan", "artistId": "artist-23", "album": "Anjaana Anjaani", "duration": 279, "youtubeVideoId": "3m4n5b6v7c9", "genre": "Sufi", "mood": "Late Night", "bpm": 80, "danceability": 0.58, "energy": 0.62, "valence": 0.40, "acousticness": 0.45, "vibeScore": 0.94 },
  { "title": "Dooriyan", "artist": "Mohit Chauhan", "artistId": "artist-23", "album": "Love Aaj Kal", "duration": 338, "youtubeVideoId": "9x0z1a2s3d5", "genre": "Acoustic", "mood": "Nostalgic", "bpm": 84, "danceability": 0.60, "energy": 0.54, "valence": 0.55, "acousticness": 0.55, "vibeScore": 0.93 },

  # Atif Aslam
  { "title": "Aadat", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Jal Pari", "duration": 268, "youtubeVideoId": "8b9a0c1d2e3", "genre": "Rock", "mood": "Late Night", "bpm": 86, "danceability": 0.54, "energy": 0.70, "valence": 0.42, "acousticness": 0.38, "vibeScore": 0.97 },
  { "title": "Woh Lamhe", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Zeher", "duration": 321, "youtubeVideoId": "4f5g6h7j8k9", "genre": "Rock", "mood": "Late Night", "bpm": 88, "danceability": 0.58, "energy": 0.74, "valence": 0.45, "acousticness": 0.32, "vibeScore": 0.96 },
  { "title": "Tere Bin", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Bas Ek Pal", "duration": 274, "youtubeVideoId": "0l1k2j3h4g5", "genre": "Romantic", "mood": "Late Night", "bpm": 82, "danceability": 0.60, "energy": 0.62, "valence": 0.48, "acousticness": 0.44, "vibeScore": 0.95 },
  { "title": "Pehli Nazar Mein", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Race", "duration": 314, "youtubeVideoId": "6m7n8b9v0c1", "genre": "Romantic", "mood": "Romantic", "bpm": 92, "danceability": 0.68, "energy": 0.70, "valence": 0.75, "acousticness": 0.28, "vibeScore": 0.95 },
  { "title": "Tu Jaane Na", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Ajab Prem Ki Ghazab Kahani", "duration": 341, "youtubeVideoId": "2q3w4e5r6t0", "genre": "Romantic", "mood": "Romantic", "bpm": 84, "danceability": 0.62, "energy": 0.60, "valence": 0.60, "acousticness": 0.42, "vibeScore": 0.96 },
  { "title": "Jeene Laga Hoon", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Ramaiya Vastavaiya", "duration": 236, "youtubeVideoId": "8y9u0i1o2p5", "genre": "Romantic", "mood": "Romantic", "bpm": 98, "danceability": 0.74, "energy": 0.72, "valence": 0.82, "acousticness": 0.24, "vibeScore": 0.93 },
  { "title": "Dil Diyan Gallan", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Tiger Zinda Hai", "duration": 260, "youtubeVideoId": "4a5s6d7f8g3", "genre": "Romantic", "mood": "Romantic", "bpm": 86, "danceability": 0.66, "energy": 0.58, "valence": 0.72, "acousticness": 0.48, "vibeScore": 0.96 },
  { "title": "Tajdar-e-Haram", "artist": "Atif Aslam", "artistId": "artist-24", "album": "Coke Studio Season 8", "duration": 628, "youtubeVideoId": "0z1x2c3v4b7", "genre": "Sufi", "mood": "Chill", "bpm": 70, "danceability": 0.40, "energy": 0.45, "valence": 0.50, "acousticness": 0.80, "vibeScore": 0.99 },

  # Badshah
  { "title": "Kala Chashma", "artist": "Badshah", "artistId": "artist-25", "album": "Baar Baar Dekho", "duration": 187, "youtubeVideoId": "k4yXQkG2s1E", "genre": "Dance", "mood": "Euphoric", "bpm": 128, "danceability": 0.94, "energy": 0.96, "valence": 0.94, "acousticness": 0.05, "vibeScore": 0.98 },
  { "title": "Kar Gayi Chull", "artist": "Badshah", "artistId": "artist-25", "album": "Kapoor & Sons", "duration": 187, "youtubeVideoId": "NTHz9ephYTw", "genre": "Dance", "mood": "Energetic", "bpm": 124, "danceability": 0.92, "energy": 0.94, "valence": 0.92, "acousticness": 0.07, "vibeScore": 0.96 },
  { "title": "DJ Waley Babu", "artist": "Badshah", "artistId": "artist-25", "album": "DJ Waley Babu", "duration": 172, "youtubeVideoId": "6n7m8k9j0h3", "genre": "Commercial Rap", "mood": "Energetic", "bpm": 110, "danceability": 0.90, "energy": 0.92, "valence": 0.88, "acousticness": 0.08, "vibeScore": 0.94 },
  { "title": "Garmi", "artist": "Badshah", "artistId": "artist-25", "album": "Street Dancer 3D", "duration": 184, "youtubeVideoId": "2w3e4r5t6y9", "genre": "Dance", "mood": "Energetic", "bpm": 126, "danceability": 0.93, "energy": 0.95, "valence": 0.90, "acousticness": 0.06, "vibeScore": 0.95 },
  { "title": "Paani Paani", "artist": "Badshah", "artistId": "artist-25", "album": "Paani Paani", "duration": 170, "youtubeVideoId": "8u9i0o1p2q5", "genre": "Commercial Rap", "mood": "Energetic", "bpm": 108, "danceability": 0.88, "energy": 0.90, "valence": 0.86, "acousticness": 0.10, "vibeScore": 0.93 },
  { "title": "Jugnu", "artist": "Badshah", "artistId": "artist-25", "album": "Jugnu", "duration": 230, "youtubeVideoId": "4a5s6d7f8g4", "genre": "Pop", "mood": "Euphoric", "bpm": 120, "danceability": 0.90, "energy": 0.92, "valence": 0.91, "acousticness": 0.08, "vibeScore": 0.94 },
  { "title": "Genda Phool", "artist": "Badshah", "artistId": "artist-25", "album": "Genda Phool", "duration": 170, "youtubeVideoId": "0h1j2k3l4m7", "genre": "Folk", "mood": "Euphoric", "bpm": 115, "danceability": 0.89, "energy": 0.91, "valence": 0.89, "acousticness": 0.12, "vibeScore": 0.93 },
  { "title": "Abhi Toh Party Shuru Hui Hai", "artist": "Badshah", "artistId": "artist-25", "album": "Khoobsurat", "duration": 180, "youtubeVideoId": "6n7b8v9c0x3", "genre": "Dance", "mood": "Euphoric", "bpm": 128, "danceability": 0.92, "energy": 0.95, "valence": 0.93, "acousticness": 0.06, "vibeScore": 0.96 },

  # Jubin Nautiyal
  { "title": "Raataan Lambiyan", "artist": "Jubin Nautiyal", "artistId": "artist-26", "album": "Shershaah", "duration": 230, "youtubeVideoId": "gvyUuxdRdR4", "genre": "Romantic", "mood": "Romantic", "bpm": 86, "danceability": 0.65, "energy": 0.62, "valence": 0.70, "acousticness": 0.40, "vibeScore": 0.96 },
  { "title": "Lut Gaye", "artist": "Jubin Nautiyal", "artistId": "artist-26", "album": "Lut Gaye", "duration": 228, "youtubeVideoId": "sCbbMZ-q4-I", "genre": "Romantic", "mood": "Late Night", "bpm": 84, "danceability": 0.62, "energy": 0.68, "valence": 0.50, "acousticness": 0.38, "vibeScore": 0.95 },
  { "title": "Tum Hi Aana", "artist": "Jubin Nautiyal", "artistId": "artist-26", "album": "Marjaavaan", "duration": 249, "youtubeVideoId": "2q3w4e5r6t9", "genre": "Romantic", "mood": "Late Night", "bpm": 80, "danceability": 0.55, "energy": 0.58, "valence": 0.42, "acousticness": 0.50, "vibeScore": 0.93 },
  { "title": "Humnava Mere", "artist": "Jubin Nautiyal", "artistId": "artist-26", "album": "Humnava Mere", "duration": 340, "youtubeVideoId": "8y9u0i1o2p6", "genre": "Romantic", "mood": "Late Night", "bpm": 78, "danceability": 0.52, "energy": 0.54, "valence": 0.38, "acousticness": 0.58, "vibeScore": 0.92 },
  { "title": "Kinna Sona", "artist": "Jubin Nautiyal", "artistId": "artist-26", "album": "Marjaavaan", "duration": 273, "youtubeVideoId": "4a5s6d7f8g5", "genre": "Romantic", "mood": "Romantic", "bpm": 88, "danceability": 0.68, "energy": 0.65, "valence": 0.75, "acousticness": 0.34, "vibeScore": 0.91 },

  # Shreya Ghoshal
  { "title": "Teri Ore", "artist": "Shreya Ghoshal", "artistId": "artist-27", "album": "Singh Is Kinng", "duration": 339, "youtubeVideoId": "1z2x3c4v5b8", "genre": "Romantic", "mood": "Romantic", "bpm": 88, "danceability": 0.68, "energy": 0.64, "valence": 0.75, "acousticness": 0.45, "vibeScore": 0.97 },
  { "title": "Deewani Mastani", "artist": "Shreya Ghoshal", "artistId": "artist-27", "album": "Bajirao Mastani", "duration": 340, "youtubeVideoId": "7n8m9k0j1h4", "genre": "Classical", "mood": "Euphoric", "bpm": 105, "danceability": 0.75, "energy": 0.85, "valence": 0.80, "acousticness": 0.30, "vibeScore": 0.97 },
  { "title": "Ghoomar", "artist": "Shreya Ghoshal", "artistId": "artist-27", "album": "Padmaavat", "duration": 281, "youtubeVideoId": "3q4w5e6r7t0", "genre": "Folk", "mood": "Euphoric", "bpm": 120, "danceability": 0.82, "energy": 0.90, "valence": 0.85, "acousticness": 0.22, "vibeScore": 0.96 },
  { "title": "Sunn Raha Hai", "artist": "Shreya Ghoshal", "artistId": "artist-27", "album": "Aashiqui 2", "duration": 314, "youtubeVideoId": "9u0i1o2p3q6", "genre": "Romantic", "mood": "Late Night", "bpm": 80, "danceability": 0.52, "energy": 0.55, "valence": 0.38, "acousticness": 0.60, "vibeScore": 0.94 },
  { "title": "Barso Re", "artist": "Shreya Ghoshal", "artistId": "artist-27", "album": "Guru", "duration": 329, "youtubeVideoId": "5a6s7d8f9g2", "genre": "Folk", "mood": "Euphoric", "bpm": 115, "danceability": 0.84, "energy": 0.88, "valence": 0.90, "acousticness": 0.25, "vibeScore": 0.96 },
  { "title": "Dola Re Dola", "artist": "Shreya Ghoshal", "artistId": "artist-27", "album": "Devdas", "duration": 397, "youtubeVideoId": "1h2j3k4l5m8", "genre": "Classical", "mood": "Euphoric", "bpm": 128, "danceability": 0.86, "energy": 0.92, "valence": 0.92, "acousticness": 0.15, "vibeScore": 0.98 },
  { "title": "Saans", "artist": "Shreya Ghoshal", "artistId": "artist-27", "album": "Jab Tak Hai Jaan", "duration": 328, "youtubeVideoId": "7z8x9c0v1b4", "genre": "Romantic", "mood": "Romantic", "bpm": 82, "danceability": 0.58, "energy": 0.52, "valence": 0.55, "acousticness": 0.58, "vibeScore": 0.93 },

  # KK
  { "title": "Zara Sa", "artist": "KK", "artistId": "artist-28", "album": "Jannat", "duration": 303, "youtubeVideoId": "5yXQ_D8i1d0", "genre": "Rock", "mood": "Romantic", "bpm": 92, "danceability": 0.65, "energy": 0.72, "valence": 0.68, "acousticness": 0.30, "vibeScore": 0.97 },
  { "title": "Labon Ko", "artist": "KK", "artistId": "artist-28", "album": "Bhool Bhulaiyaa", "duration": 344, "youtubeVideoId": "3m4n5b6v7c0", "genre": "Romantic", "mood": "Romantic", "bpm": 86, "danceability": 0.62, "energy": 0.65, "valence": 0.64, "acousticness": 0.38, "vibeScore": 0.96 },
  { "title": "Kya Mujhe Pyaar Hai", "artist": "KK", "artistId": "artist-28", "album": "Woh Lamhe", "duration": 279, "youtubeVideoId": "9x0z1a2s3d6", "genre": "Rock", "mood": "Romantic", "bpm": 110, "danceability": 0.74, "energy": 0.82, "valence": 0.78, "acousticness": 0.20, "vibeScore": 0.97 },
  { "title": "Alvida", "artist": "KK", "artistId": "artist-28", "album": "Life in a... Metro", "duration": 340, "youtubeVideoId": "5f6g7h8j9k1", "genre": "Rock", "mood": "Late Night", "bpm": 88, "danceability": 0.56, "energy": 0.80, "valence": 0.44, "acousticness": 0.28, "vibeScore": 0.98 },
  { "title": "Aankhon Mein Teri", "artist": "KK", "artistId": "artist-28", "album": "Om Shanti Om", "duration": 242, "youtubeVideoId": "1a2s3d4f5g8", "genre": "Romantic", "mood": "Romantic", "bpm": 84, "danceability": 0.64, "energy": 0.58, "valence": 0.72, "acousticness": 0.48, "vibeScore": 0.98 },
  { "title": "Tu Hi Meri Shab Hai", "artist": "KK", "artistId": "artist-28", "album": "Gangster", "duration": 388, "youtubeVideoId": "7h8j9k0l1m4", "genre": "Rock", "mood": "Romantic", "bpm": 86, "danceability": 0.60, "energy": 0.70, "valence": 0.62, "acousticness": 0.35, "vibeScore": 0.96 },
  { "title": "Sach Keh Raha Hai", "artist": "KK", "artistId": "artist-28", "album": "Rehnaa Hai Terre Dil Mein", "duration": 327, "youtubeVideoId": "3l4m5n6o7p0", "genre": "Soul", "mood": "Late Night", "bpm": 76, "danceability": 0.50, "energy": 0.48, "valence": 0.32, "acousticness": 0.65, "vibeScore": 0.98 },
  { "title": "Dil Ibaadat", "artist": "KK", "artistId": "artist-28", "album": "Tum Mile", "duration": 329, "youtubeVideoId": "9q8w7e6r5t6", "genre": "Rock", "mood": "Romantic", "bpm": 88, "danceability": 0.62, "energy": 0.72, "valence": 0.66, "acousticness": 0.32, "vibeScore": 0.97 },

  # Sonu Nigam
  { "title": "Kal Ho Naa Ho", "artist": "Sonu Nigam", "artistId": "artist-29", "album": "Kal Ho Naa Ho", "duration": 322, "youtubeVideoId": "g0eO74UmRBs", "genre": "Soundtrack", "mood": "Nostalgic", "bpm": 80, "danceability": 0.54, "energy": 0.58, "valence": 0.55, "acousticness": 0.58, "vibeScore": 0.99 },
  { "title": "Abhi Mujh Mein Kahin", "artist": "Sonu Nigam", "artistId": "artist-29", "album": "Agneepath", "duration": 364, "youtubeVideoId": "o1Rkpu0vW3I", "genre": "Soundtrack", "mood": "Nostalgic", "bpm": 75, "danceability": 0.48, "energy": 0.52, "valence": 0.45, "acousticness": 0.72, "vibeScore": 0.99 },
  { "title": "Suraj Hua Maddham", "artist": "Sonu Nigam", "artistId": "artist-29", "album": "Kabhi Khushi Kabhie Gham", "duration": 428, "youtubeVideoId": "2y3u4i5o6p9", "genre": "Romantic", "mood": "Romantic", "bpm": 82, "danceability": 0.58, "energy": 0.54, "valence": 0.64, "acousticness": 0.55, "vibeScore": 0.98 },
  { "title": "Bole Chudiyan", "artist": "Sonu Nigam", "artistId": "artist-29", "album": "Kabhi Khushi Kabhie Gham", "duration": 404, "youtubeVideoId": "8a9s0d1f2g5", "genre": "Dance", "mood": "Euphoric", "bpm": 125, "danceability": 0.88, "energy": 0.92, "valence": 0.94, "acousticness": 0.12, "vibeScore": 0.97 },
  { "title": "Tumse Milke Dil Ka", "artist": "Sonu Nigam", "artistId": "artist-29", "album": "Main Hoon Na", "duration": 360, "youtubeVideoId": "4h5j6k7l8m1", "genre": "Qawwali", "mood": "Euphoric", "bpm": 130, "danceability": 0.89, "energy": 0.94, "valence": 0.95, "acousticness": 0.08, "vibeScore": 0.98 },
  { "title": "Main Agar Kahoon", "artist": "Sonu Nigam", "artistId": "artist-29", "album": "Om Shanti Om", "duration": 310, "youtubeVideoId": "0z1x2c3v4b8", "genre": "Romantic", "mood": "Romantic", "bpm": 84, "danceability": 0.62, "energy": 0.55, "valence": 0.68, "acousticness": 0.50, "vibeScore": 0.97 },
  { "title": "Saathiya", "artist": "Sonu Nigam", "artistId": "artist-29", "album": "Saathiya", "duration": 357, "youtubeVideoId": "6n7m8k9j0h4", "genre": "Soundtrack", "mood": "Romantic", "bpm": 86, "danceability": 0.66, "energy": 0.62, "valence": 0.72, "acousticness": 0.44, "vibeScore": 0.97 },

  # Vishal-Shekhar
  { "title": "Desi Girl", "artist": "Vishal-Shekhar", "artistId": "artist-30", "album": "Dostana", "duration": 306, "youtubeVideoId": "cwmk3Z2v4b5", "genre": "Dance", "mood": "Euphoric", "bpm": 128, "danceability": 0.92, "energy": 0.96, "valence": 0.94, "acousticness": 0.06, "vibeScore": 0.97 },
  { "title": "Ghungroo", "artist": "Vishal-Shekhar", "artistId": "artist-30", "album": "War", "duration": 302, "youtubeVideoId": "qFkNATnc3mc", "genre": "Dance", "mood": "Euphoric", "bpm": 118, "danceability": 0.90, "energy": 0.92, "valence": 0.92, "acousticness": 0.08, "vibeScore": 0.96 },
  { "title": "Nashe Si Chadh Gayi", "artist": "Vishal-Shekhar", "artistId": "artist-30", "album": "Befikre", "duration": 238, "youtubeVideoId": "Wd2B8OAotU8", "genre": "Dance", "mood": "Euphoric", "bpm": 112, "danceability": 0.88, "energy": 0.89, "valence": 0.90, "acousticness": 0.10, "vibeScore": 0.95 },
  { "title": "Swag Se Swagat", "artist": "Vishal-Shekhar", "artistId": "artist-30", "album": "Tiger Zinda Hai", "duration": 236, "youtubeVideoId": "xmU0s2QtaEY", "genre": "Dance", "mood": "Euphoric", "bpm": 120, "danceability": 0.89, "energy": 0.94, "valence": 0.91, "acousticness": 0.07, "vibeScore": 0.95 },
  { "title": "Jhoome Jo Pathaan", "artist": "Vishal-Shekhar", "artistId": "artist-30", "album": "Pathaan", "duration": 208, "youtubeVideoId": "YxWlaYCA8MU", "genre": "Dance", "mood": "Euphoric", "bpm": 116, "danceability": 0.89, "energy": 0.93, "valence": 0.92, "acousticness": 0.08, "vibeScore": 0.96 },
  { "title": "Besharam Rang", "artist": "Vishal-Shekhar", "artistId": "artist-30", "album": "Pathaan", "duration": 258, "youtubeVideoId": "huxhqphtDrM", "genre": "Dance", "mood": "Energetic", "bpm": 122, "danceability": 0.88, "energy": 0.90, "valence": 0.85, "acousticness": 0.12, "vibeScore": 0.94 },

  # Amit Trivedi
  { "title": "Namo Namo", "artist": "Amit Trivedi", "artistId": "artist-31", "album": "Kedarnath", "duration": 322, "youtubeVideoId": "dx4Teh-nv3A", "genre": "Devotional", "mood": "Empowering", "bpm": 88, "danceability": 0.60, "energy": 0.78, "valence": 0.70, "acousticness": 0.40, "vibeScore": 0.97 },
  { "title": "Iktara", "artist": "Amit Trivedi", "artistId": "artist-31", "album": "Wake Up Sid", "duration": 253, "youtubeVideoId": "fSS_R91Nimw", "genre": "Indie Folk", "mood": "Chill", "bpm": 85, "danceability": 0.68, "energy": 0.58, "valence": 0.74, "acousticness": 0.52, "vibeScore": 0.96 },
  { "title": "London Thumakda", "artist": "Amit Trivedi", "artistId": "artist-31", "album": "Queen", "duration": 230, "youtubeVideoId": "draA3PUoaU4", "genre": "Folk", "mood": "Euphoric", "bpm": 128, "danceability": 0.91, "energy": 0.96, "valence": 0.95, "acousticness": 0.06, "vibeScore": 0.97 },
  { "title": "Qaafirana", "artist": "Amit Trivedi", "artistId": "artist-31", "album": "Kedarnath", "duration": 342, "youtubeVideoId": "Z1BCujX3pw8", "genre": "Romantic", "mood": "Romantic", "bpm": 82, "danceability": 0.62, "energy": 0.56, "valence": 0.65, "acousticness": 0.50, "vibeScore": 0.94 }
]
