import fs from 'fs';
import path from 'path';

// Define the comprehensive Artist Database (70+ top artists)
const ARTISTS = [
  // Punjabi
  { id: 'artist-1', name: 'AP Dhillon', genres: ['Punjabi Pop', 'Hip-Hop', 'Trap'], bio: 'Indo-Canadian singer and producer known for hits like Excuses, Brown Munde, and With You.', monthlyListeners: '8.4M', country: 'Canada/India', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-2', name: 'Diljit Dosanjh', genres: ['Punjabi Pop', 'Bhangra', 'Folk'], bio: 'Global Punjabi superstar, actor, and historic Coachella performer.', monthlyListeners: '14.2M', country: 'India', image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-3', name: 'Karan Aujla', genres: ['Punjabi Rap', 'Desi Hip Hop', 'Folk'], bio: 'Chart-topping Punjabi singer and lyricist known for Four You and Making Memories.', monthlyListeners: '11.8M', country: 'Canada/India', image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-4', name: 'Shubh', genres: ['Punjabi Hip Hop', 'Trap', 'Melodic Rap'], bio: 'Sensational Punjabi breakout star behind Still Rollin, Cheques, and Baller.', monthlyListeners: '9.6M', country: 'India', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-5', name: 'Sidhu Moose Wala', genres: ['Punjabi Hip Hop', 'Gangsta Rap', 'Folk'], bio: 'Iconic and influential Punjabi revolutionary rapper and songwriter.', monthlyListeners: '12.5M', country: 'India', image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-6', name: 'Guru Randhawa', genres: ['Punjabi Pop', 'Dance', 'Bollywood'], bio: 'High-energy Punjabi hitmaker behind Lahore, High Rated Gabru, and Suit.', monthlyListeners: '7.8M', country: 'India', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-7', name: 'Harrdy Sandhu', genres: ['Punjabi Pop', 'Romantic', 'Dance'], bio: 'Celebrated singer known for Bijlee Bijlee, Backbone, and Soch.', monthlyListeners: '6.2M', country: 'India', image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-8', name: 'Ammy Virk', genres: ['Punjabi Folk', 'Bhangra', 'Melody'], bio: 'Award-winning Punjabi folk singer and actor with deep emotive vocals.', monthlyListeners: '5.5M', country: 'India', image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-9', name: 'B Praak', genres: ['Sufi', 'Punjabi Sad', 'Bollywood'], bio: 'National Award-winning music composer and singer behind Teri Mitti and Filhall.', monthlyListeners: '8.9M', country: 'India', image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-10', name: 'Imran Khan', genres: ['Desi Hip Hop', 'Urban Punjabi', 'R&B'], bio: 'Pioneering Dutch-Pakistani singer who revolutionized urban Punjabi music with Amplifier.', monthlyListeners: '4.8M', country: 'Netherlands', image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-11', name: 'Panjabi MC', genres: ['Bhangra', 'Hip-Hop', 'UK Asian'], bio: 'World-renowned British-Indian producer behind the global anthem Mundian To Bach Ke.', monthlyListeners: '3.9M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-12', name: 'Daler Mehndi', genres: ['Bhangra', 'Indipop', 'Folk'], bio: 'The pioneer of modern Bhangra and global viral pop with Tunak Tunak Tun.', monthlyListeners: '3.2M', country: 'India', image: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-13', name: 'Jasmine Sandlas', genres: ['Punjabi Pop', 'Folk', 'Hip-Hop'], bio: 'The Gulabi Queen known for bold, fiery anthems like Illegal Weapon and Sip Sip.', monthlyListeners: '3.7M', country: 'India', image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-14', name: 'Nimrat Khaira', genres: ['Punjabi Folk', 'Pop', 'Melody'], bio: 'Versatile vocalist celebrated for timeless folk grooves and modern pop hits.', monthlyListeners: '4.1M', country: 'India', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-15', name: 'Sunanda Sharma', genres: ['Punjabi Pop', 'Dance', 'Bhangra'], bio: 'High-spirit Punjabi powerhouse behind Jaani Tera Naa and Duji Vaar Pyar.', monthlyListeners: '3.4M', country: 'India', image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-16', name: 'Mickey Singh', genres: ['Urban Desi', 'R&B', 'Punjabi Pop'], bio: 'American singer blending smooth western R&B with Punjabi melodies.', monthlyListeners: '2.9M', country: 'United States', image: 'https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-17', name: 'Prem Dhillon', genres: ['Punjabi Hip Hop', 'Trap'], bio: 'Majha representative delivering raw, hard-hitting bangers like Old Skool.', monthlyListeners: '3.6M', country: 'India', image: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-18', name: 'Bohemia', genres: ['Desi Hip Hop', 'Rap Pioneer'], bio: 'The creator of Desi Hip Hop with a legendary discography.', monthlyListeners: '4.5M', country: 'United States', image: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  
  // Bollywood & Hindi
  { id: 'artist-19', name: 'Arijit Singh', genres: ['Bollywood', 'Romantic', 'Sufi'], bio: 'India’s foremost playback legend celebrated for soulful romantic melodies.', monthlyListeners: '42.0M', country: 'India', image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-20', name: 'A.R. Rahman', genres: ['World', 'Soundtrack', 'Sufi', 'Fusion'], bio: 'Oscar and Grammy-winning musical maestro who redefined Indian music globally.', monthlyListeners: '18.5M', country: 'India', image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-21', name: 'Pritam', genres: ['Bollywood', 'Pop', 'Rock'], bio: 'Prolific Bollywood composer behind dozens of era-defining blockbuster albums.', monthlyListeners: '26.0M', country: 'India', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-22', name: 'Mohit Chauhan', genres: ['Bollywood', 'Indipop', 'Folk'], bio: 'Velveteen voice of iconic soundtracks like Rockstar and Jab We Met.', monthlyListeners: '9.2M', country: 'India', image: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-23', name: 'Atif Aslam', genres: ['Bollywood', 'Sufi Rock', 'Romantic'], bio: 'Sensational Pakistani vocal powerhouse behind countless timeless anthems.', monthlyListeners: '16.8M', country: 'Pakistan', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-24', name: 'Badshah', genres: ['Desi Hip Hop', 'Commercial Rap', 'Pop'], bio: 'Multi-platinum Indian rapper and party anthem king with billions of streams.', monthlyListeners: '15.4M', country: 'India', image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-25', name: 'Jubin Nautiyal', genres: ['Bollywood', 'Acoustic', 'Devotional'], bio: 'Chart-topping romantic vocalist known for Raataan Lambiyan and Lut Gaye.', monthlyListeners: '13.1M', country: 'India', image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-26', name: 'Shreya Ghoshal', genres: ['Bollywood', 'Classical', 'Romantic'], bio: 'Four-time National Award-winning queen of Indian playback melody.', monthlyListeners: '28.5M', country: 'India', image: 'https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-27', name: 'KK', genres: ['Bollywood', 'Rock', 'Soul'], bio: 'Beloved voice of a generation whose anthems defined youth and nostalgia.', monthlyListeners: '12.0M', country: 'India', image: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-28', name: 'Sonu Nigam', genres: ['Bollywood', 'Ghazal', 'Pop'], bio: 'One of Indian music history’s most versatile and acclaimed vocalists.', monthlyListeners: '11.5M', country: 'India', image: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-29', name: 'Vishal-Shekhar', genres: ['Bollywood', 'Dance', 'Electro-pop'], bio: 'Dynamic composer duo creating high-octane Bollywood dance anthems.', monthlyListeners: '14.0M', country: 'India', image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-30', name: 'Amit Trivedi', genres: ['Bollywood', 'Indie Rock', 'Experimental'], bio: 'Genius music director bringing organic rustic depth to Indian cinema.', monthlyListeners: '8.7M', country: 'India', image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },

  // Indian Indie
  { id: 'artist-31', name: 'Prateek Kuhad', genres: ['Indie Folk', 'Acoustic Pop', 'Singer-Songwriter'], bio: 'International indie-folk sensation behind cold/mess and Kasoor.', monthlyListeners: '4.2M', country: 'India', image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-32', name: 'Anuv Jain', genres: ['Indie Acoustic', 'Poetry', 'Ballad'], bio: 'Gentle acoustic storyteller who captured India with Baarishein and Husn.', monthlyListeners: '6.8M', country: 'India', image: 'https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-33', name: 'The Local Train', genres: ['Hindi Rock', 'Indie Rock'], bio: 'Cult-favorite Hindi rock band celebrated for Choo Lo and Aaoge Tum Kabhi.', monthlyListeners: '3.1M', country: 'India', image: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-34', name: 'Ritviz', genres: ['Indian Electronic', 'Dance', 'Folk Fusion'], bio: 'Electronic music pioneer weaving Indian classical melodies into festival bangers.', monthlyListeners: '4.5M', country: 'India', image: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-35', name: 'When Chai Met Toast', genres: ['Indie Folk', 'Acoustic Pop'], bio: 'Kochi-based band creating joyful, uplifting multilingual indie acoustic anthems.', monthlyListeners: '1.9M', country: 'India', image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-36', name: 'Seedhe Maut', genres: ['Desi Hip Hop', 'Underground Rap'], bio: 'Delhi rap duo delivering razor-sharp lyricism and unmatched underground energy.', monthlyListeners: '2.5M', country: 'India', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-37', name: 'DIVINE', genres: ['Gully Rap', 'Desi Hip Hop'], bio: 'The pioneer who put Mumbai Gully Rap onto the worldwide map.', monthlyListeners: '5.6M', country: 'India', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-38', name: 'Dream Note', genres: ['Indie Pop', 'Melancholy'], bio: 'Jaipur indie ensemble known for soulful introspection in Waqt Ki Baatein.', monthlyListeners: '1.5M', country: 'India', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },

  // South Indian & Regional
  { id: 'artist-39', name: 'Anirudh Ravichander', genres: ['Tamil Pop', 'Soundtrack', 'Electronic'], bio: 'Rockstar composer ruling South Indian cinema with adrenaline-pumping hits.', monthlyListeners: '17.2M', country: 'India', image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-40', name: 'Sid Sriram', genres: ['Carnatic Fusion', 'Soul', 'Tamil/Telugu'], bio: 'Indian-American singer renowned for his transcendent vocal range across languages.', monthlyListeners: '10.5M', country: 'India', image: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-41', name: 'Devi Sri Prasad (DSP)', genres: ['Telugu Pop', 'Soundtrack', 'Dance'], bio: 'Energy-packed musical maestro behind Pushpa and iconic Telugu chartbusters.', monthlyListeners: '8.3M', country: 'India', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-42', name: 'Sushin Shyam', genres: ['Malayalam Film Score', 'Synthwave', 'Indie'], bio: 'Visionary composer leading the modern musical renaissance of Malayalam cinema.', monthlyListeners: '5.1M', country: 'India', image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-43', name: 'Ajay-Atul', genres: ['Marathi Film Score', 'Orchestral', 'Folk'], bio: 'Celebrated composer brothers famous for the monumental masterpiece Zingaat.', monthlyListeners: '4.8M', country: 'India', image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-44', name: 'Sachin-Jigar', genres: ['Gujarati Pop', 'Bollywood', 'Dance'], bio: 'Versatile composer duo revitalizing modern Gujarati music and Bollywood hits.', monthlyListeners: '7.9M', country: 'India', image: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },

  // Global Pop, Hip-Hop & R&B
  { id: 'artist-45', name: 'The Weeknd', genres: ['R&B', 'Synth-pop', 'Pop'], bio: 'Global pop superstar behind Blinding Lights and Starboy.', monthlyListeners: '108.0M', country: 'Canada', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-46', name: 'Drake', genres: ['Hip-Hop', 'Trap', 'R&B'], bio: 'One of the most commercially successful hip-hop artists in streaming history.', monthlyListeners: '82.0M', country: 'Canada', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-47', name: 'Dua Lipa', genres: ['Pop', 'Disco', 'Dance-pop'], bio: 'Grammy-winning queen of Future Nostalgia and modern electro-disco.', monthlyListeners: '65.0M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-48', name: 'Post Malone', genres: ['Pop', 'Hip-Hop', 'Country Rock'], bio: 'Genre-bending superstar with multiple diamond-certified global hits.', monthlyListeners: '72.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-49', name: 'Billie Eilish', genres: ['Alt Pop', 'Electropop'], bio: 'Nine-time Grammy winner celebrated for whispery, bass-heavy production.', monthlyListeners: '95.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-50', name: 'Travis Scott', genres: ['Trap', 'Psychedelic Rap'], bio: 'Astroworld mastermind crafting monumental, chaotic rap soundscapes.', monthlyListeners: '68.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-51', name: 'Kendrick Lamar', genres: ['Conscious Hip-Hop', 'West Coast Rap'], bio: 'Pulitzer Prize-winning rap icon known for technical brilliance and storytelling.', monthlyListeners: '62.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-52', name: 'Harry Styles', genres: ['Pop Rock', 'Britpop'], bio: 'Solo sensation bringing vintage 70s flair to modern global pop.', monthlyListeners: '52.0M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-53', name: 'Taylor Swift', genres: ['Pop', 'Country', 'Indie Folk'], bio: 'The definitive musical titan of the 21st century across 11 studio eras.', monthlyListeners: '102.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-54', name: 'Ed Sheeran', genres: ['Pop', 'Acoustic', 'Folk Pop'], bio: 'Record-breaking singer-songwriter behind Shape of You and Perfect.', monthlyListeners: '74.0M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-55', name: 'Bruno Mars', genres: ['Funk', 'Pop', 'Soul'], bio: 'Modern funk and soul virtuoso with an unbroken string of worldwide #1s.', monthlyListeners: '88.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-56', name: 'Ariana Grande', genres: ['Pop', 'R&B', 'Dance-pop'], bio: 'Four-octave vocal powerhouse with era-defining pop and R&B smashes.', monthlyListeners: '78.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-57', name: 'SZA', genres: ['R&B', 'Neo-soul', 'Alt R&B'], bio: 'SOS chart-topper crafting deeply honest and hypnotic modern soul anthems.', monthlyListeners: '67.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-58', name: 'Justin Bieber', genres: ['Pop', 'R&B', 'Dance'], bio: 'One of the best-selling artists in music history with dozens of iconic hits.', monthlyListeners: '70.0M', country: 'Canada', image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-59', name: 'Rihanna', genres: ['R&B', 'Pop', 'Dancehall'], bio: 'Barbadian icon with 14 Billboard Hot 100 #1 singles.', monthlyListeners: '76.0M', country: 'Barbados', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },

  // Classics, Rock & EDM
  { id: 'artist-60', name: 'Coldplay', genres: ['Alt Rock', 'Pop Rock'], bio: 'British stadium-rock legends behind Yellow, Fix You, and Viva La Vida.', monthlyListeners: '85.0M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-61', name: 'Queen', genres: ['Classic Rock', 'Glam Rock'], bio: 'Legendary British rock band fronted by the incomparable Freddie Mercury.', monthlyListeners: '48.0M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-62', name: 'Arctic Monkeys', genres: ['Indie Rock', 'Garage Rock'], bio: 'Sheffield indie rock heavyweights behind Do I Wanna Know? and AM.', monthlyListeners: '46.0M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-63', name: 'Linkin Park', genres: ['Nu Metal', 'Alt Rock'], bio: 'Groundbreaking rock band uniting aggressive rock, rap, and electronic music.', monthlyListeners: '43.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-64', name: 'Avicii', genres: ['EDM', 'Progressive House', 'Melodic Dance'], bio: 'Swedish electronic genius who touched the world with Wake Me Up and Levels.', monthlyListeners: '35.0M', country: 'Sweden', image: 'https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-65', name: 'The Chainsmokers', genres: ['EDM Pop', 'Future Bass'], bio: 'EDM-pop duo behind multi-billion streaming hits Closer and Paris.', monthlyListeners: '44.0M', country: 'United States', image: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-66', name: 'Calvin Harris', genres: ['EDM', 'Dance-pop', 'Electro House'], bio: 'World-leading Scottish producer and DJ with Summer and One Kiss.', monthlyListeners: '61.0M', country: 'United Kingdom', image: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' },
  { id: 'artist-67', name: 'Martin Garrix', genres: ['Big Room House', 'Progressive House'], bio: 'Four-time #1 DJ in the world known for Animals and Scared to Be Lonely.', monthlyListeners: '27.0M', country: 'Netherlands', image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80', imageSource: 'Verified Promo' }
];

console.log(`Configured ${ARTISTS.length} canonical artists.`);
